using ExportDocManager.Utils;

namespace ExportDocManager.Services.SingleWindow
{
    public static partial class SingleWindowFieldMapperHelpers
    {
        public sealed record CountryCatalogEntry(string Code, string EnglishName, string ChineseName, params string[] Aliases);

        private sealed record AcdCountryCatalogEntry(string Code, string ChineseName, string EnglishName, params string[] Aliases);

        private sealed record CurrencyCatalogEntry(string Code, string AcdCode, string AlphaCode, params string[] Aliases);

        private sealed record AcdTradeModeCatalogEntry(string Code, string Name, string Description, params string[] Aliases);

        private sealed record TransportModeCatalogEntry(string Value, params string[] Aliases);

        private sealed record PortCatalogEntry(string Value, params string[] Aliases);

        private static readonly CountryCatalogEntry[] FallbackCountryCatalog =
        [
            new("032", "ARGENTINA", "阿根廷", "AR", "ARG", "ARGENTINA", "阿根廷"),
            new("036", "AUSTRALIA", "澳大利亚", "AU", "AUS", "AUSTRALIA", "澳大利亚"),
            new("050", "BANGLADESH", "孟加拉国", "BD", "BGD", "BANGLADESH", "孟加拉", "孟加拉国"),
            new("056", "BELGIUM", "比利时", "BE", "BEL", "BELGIUM", "比利时"),
            new("076", "BRAZIL", "巴西", "BR", "BRA", "BRAZIL", "巴西"),
            new("104", "MYANMAR", "缅甸", "MM", "MMR", "BURMA", "MYANMAR", "缅甸"),
            new("116", "CAMBODIA", "柬埔寨", "KH", "KHM", "CAMBODIA", "柬埔寨"),
            new("124", "CANADA", "加拿大", "CA", "CAN", "CANADA", "加拿大"),
            new("144", "SRI LANKA", "斯里兰卡", "LK", "LKA", "SRILANKA", "斯里兰卡"),
            new("152", "CHILE", "智利", "CL", "CHL", "CHILE", "智利"),
            new("156", "CHINA", "中国", "CN", "CHN", "PRC", "CHINA", "中国"),
            new("158", "TAIWAN", "中国台湾", "TW", "TWN", "TAIWAN", "中国台湾", "台湾"),
            new("178", "CONGO", "刚果(布)", "CG", "COG", "CONGO", "REPUBLICOFCONGO", "刚果", "刚果布"),
            new("188", "COSTA RICA", "哥斯达黎加", "CR", "CRI", "COSTARICA", "哥斯达黎加"),
            new("203", "CZECH REPUBLIC", "捷克", "CZ", "CZE", "CZECHIA", "CZECHREPUBLIC", "捷克"),
            new("208", "DENMARK", "丹麦", "DK", "DNK", "DENMARK", "丹麦"),
            new("218", "ECUADOR", "厄瓜多尔", "EC", "ECU", "ECUADOR", "厄瓜多尔"),
            new("246", "FINLAND", "芬兰", "FI", "FIN", "FINLAND", "芬兰"),
            new("250", "FRANCE", "法国", "FR", "FRA", "FRANCE", "法国"),
            new("268", "GEORGIA", "格鲁吉亚", "GE", "GEO", "GEORGIA", "格鲁吉亚"),
            new("276", "GERMANY", "德国", "DE", "DEU", "GERMANY", "德国"),
            new("300", "GREECE", "希腊", "GR", "GRC", "GREECE", "希腊"),
            new("340", "HONDURAS", "洪都拉斯", "HN", "HND", "HONDURAS", "洪都拉斯"),
            new("344", "HONG KONG", "中国香港", "HK", "HKG", "HONGKONG", "香港", "中国香港"),
            new("348", "HUNGARY", "匈牙利", "HU", "HUN", "HUNGARY", "匈牙利"),
            new("352", "ICELAND", "冰岛", "IS", "ISL", "ICELAND", "冰岛"),
            new("356", "INDIA", "印度", "IN", "IND", "INDIA", "印度"),
            new("360", "INDONESIA", "印度尼西亚", "ID", "IDN", "INDONESIA", "印尼", "印度尼西亚"),
            new("372", "IRELAND", "爱尔兰", "IE", "IRL", "IRELAND", "爱尔兰"),
            new("376", "ISRAEL", "以色列", "IL", "ISR", "ISRAEL", "以色列"),
            new("380", "ITALY", "意大利", "IT", "ITA", "ITALY", "意大利"),
            new("392", "JAPAN", "日本", "JP", "JPN", "JAPAN", "日本"),
            new("410", "KOREA", "韩国", "KR", "KOR", "SOUTHKOREA", "韩国", "南韩"),
            new("418", "LAOS", "老挝", "LA", "LAO", "LAOS", "老挝"),
            new("442", "LUXEMBOURG", "卢森堡", "LU", "LUX", "LUXEMBOURG", "卢森堡"),
            new("446", "MACAO", "中国澳门", "MO", "MAC", "MACAO", "MACAU", "澳门", "中国澳门"),
            new("458", "MALAYSIA", "马来西亚", "MY", "MYS", "MALAYSIA", "马来西亚"),
            new("462", "MALDIVES", "马尔代夫", "MV", "MDV", "MALDIVES", "马尔代夫"),
            new("480", "MAURITIUS", "毛里求斯", "MU", "MUS", "MAURITIUS", "毛里求斯"),
            new("484", "MEXICO", "墨西哥", "MX", "MEX", "MEXICO", "墨西哥"),
            new("496", "MONGOLIA", "蒙古", "MN", "MNG", "MONGOLIA", "蒙古"),
            new("528", "NETHERLANDS", "荷兰", "NL", "NLD", "NETHERLANDS", "荷兰"),
            new("554", "NEW ZEALAND", "新西兰", "NZ", "NZL", "NEWZEALAND", "新西兰"),
            new("558", "NICARAGUA", "尼加拉瓜", "NI", "NIC", "NICARAGUA", "尼加拉瓜"),
            new("578", "NORWAY", "挪威", "NO", "NOR", "NORWAY", "挪威"),
            new("586", "PAKISTAN", "巴基斯坦", "PK", "PAK", "PAKISTAN", "巴基斯坦"),
            new("604", "PERU", "秘鲁", "PE", "PER", "PERU", "秘鲁"),
            new("608", "PHILIPPINES", "菲律宾", "PH", "PHL", "PHILIPPINES", "菲律宾"),
            new("616", "POLAND", "波兰", "PL", "POL", "POLAND", "波兰"),
            new("620", "PORTUGAL", "葡萄牙", "PT", "PRT", "PORTUGAL", "葡萄牙"),
            new("642", "ROMANIA", "罗马尼亚", "RO", "ROU", "ROMANIA", "罗马尼亚"),
            new("643", "RUSSIA", "俄罗斯", "RU", "RUS", "RUSSIA", "俄罗斯"),
            new("688", "SERBIA", "塞尔维亚", "RS", "SRB", "SERBIA", "塞尔维亚"),
            new("682", "SAUDI ARABIA", "沙特阿拉伯", "SA", "SAU", "SAUDIARABIA", "沙特", "沙特阿拉伯"),
            new("702", "SINGAPORE", "新加坡", "SG", "SGP", "SINGAPORE", "新加坡"),
            new("704", "VIETNAM", "越南", "VN", "VNM", "VIETNAM", "越南"),
            new("710", "SOUTH AFRICA", "南非", "ZA", "ZAF", "SOUTHAFRICA", "南非"),
            new("724", "SPAIN", "西班牙", "ES", "ESP", "SPAIN", "西班牙"),
            new("752", "SWEDEN", "瑞典", "SE", "SWE", "SWEDEN", "瑞典"),
            new("756", "SWITZERLAND", "瑞士", "CH", "CHE", "SWITZERLAND", "瑞士"),
            new("764", "THAILAND", "泰国", "TH", "THA", "THAILAND", "泰国"),
            new("784", "UNITED ARAB EMIRATES", "阿联酋", "AE", "ARE", "UAE", "UNITEDARABEMIRATES", "阿联酋"),
            new("792", "TURKIYE", "土耳其", "TR", "TUR", "TURKEY", "TURKIYE", "土耳其"),
            new("818", "EGYPT", "埃及", "EG", "EGY", "EGYPT", "埃及"),
            new("826", "UNITED KINGDOM", "英国", "GB", "GBR", "UK", "UNITEDKINGDOM", "英国"),
            new("840", "UNITED STATES", "美国", "US", "USA", "UNITEDSTATES", "美国")
        ];

        private static readonly CurrencyCatalogEntry[] FallbackCurrencyCatalog =
        [
            new("032", string.Empty, "ARS", "ARGENTINEPESO", "阿根廷比索"),
            new("036", "601", "AUD", "AUSTRALIANDOLLAR", "澳元"),
            new("050", string.Empty, "BDT", "TAKA", "孟加拉塔卡"),
            new("116", string.Empty, "KHR", "RIEL", "柬埔寨瑞尔"),
            new("124", "501", "CAD", "CANADIANDOLLAR", "加元"),
            new("144", string.Empty, "LKR", "SRILANKANRUPEE", "斯里兰卡卢比"),
            new("152", string.Empty, "CLP", "CHILEANPESO", "智利比索"),
            new("188", string.Empty, "CRC", "COLON", "哥斯达黎加科朗"),
            new("203", string.Empty, "CZK", "CZECHKORUNA", "捷克克朗"),
            new("208", "302", "DKK", "DANISHKRONE", "丹麦克朗"),
            new("156", "142", "CNY", "RMB", "RENMINBI", "YUAN", "人民币"),
            new("268", string.Empty, "GEL", "LARI", "格鲁吉亚拉里"),
            new("344", "110", "HKD", "HONGKONGDOLLAR", "港币", "港元"),
            new("348", string.Empty, "HUF", "FORINT", "匈牙利福林"),
            new("352", string.Empty, "ISK", "ICELANDKRONA", "冰岛克朗"),
            new("356", string.Empty, "INR", "INDIANRUPEE", "印度卢比"),
            new("360", string.Empty, "IDR", "INDONESIANRUPIAH", "印尼盾"),
            new("376", string.Empty, "ILS", "ISRAELISHEKEL", "以色列新谢克尔", "新谢克尔"),
            new("392", "116", "JPY", "YEN", "日元"),
            new("410", "133", "KRW", "WON", "韩元"),
            new("418", string.Empty, "LAK", "KIP", "老挝基普"),
            new("458", string.Empty, "MYR", "RINGGIT", "马币", "林吉特"),
            new("462", string.Empty, "MVR", "RUFIYAA", "马尔代夫拉菲亚"),
            new("484", string.Empty, "MXN", "MEXICANPESO", "墨西哥比索"),
            new("480", string.Empty, "MUR", "MAURITIANRUPEE", "毛里求斯卢比"),
            new("554", "609", "NZD", "NEWZEALANDDOLLAR", "新西兰元"),
            new("558", string.Empty, "NIO", "CORDOBA", "尼加拉瓜科多巴"),
            new("608", "129", "PHP", "PESO", "菲律宾比索"),
            new("578", "326", "NOK", "NORWEGIANKRONE", "挪威克朗"),
            new("586", string.Empty, "PKR", "PAKISTANIRUPEE", "巴基斯坦卢比"),
            new("604", string.Empty, "PEN", "SOL", "秘鲁索尔"),
            new("688", string.Empty, "RSD", "SERBIANDINAR", "塞尔维亚第纳尔"),
            new("702", "132", "SGD", "SINGAPOREDOLLAR", "新加坡元"),
            new("710", string.Empty, "ZAR", "RAND", "南非兰特"),
            new("752", "330", "SEK", "SWEDISHKRONA", "瑞典克朗"),
            new("756", "331", "CHF", "SWISSFRANC", "瑞士法郎"),
            new("764", "136", "THB", "BAHT", "泰铢"),
            new("784", string.Empty, "AED", "DIRHAM", "阿联酋迪拉姆", "迪拉姆"),
            new("818", string.Empty, "EGP", "EGYPTIANPOUND", "埃及镑"),
            new("826", "303", "GBP", "POUND", "英镑"),
            new("840", "502", "USD", "DOLLAR", "美金", "美元"),
            new("986", string.Empty, "BRL", "BRAZILIANREAL", "巴西雷亚尔"),
            new("978", "300", "EUR", "EURO", "欧元")
        ];

        private static readonly AcdCountryCatalogEntry[] FallbackAcdCountryCatalog =
        [
            new("101", "阿富汗", "Afghanistan", "AFGHANISTAN", "阿富汗"),
            new("102", "巴林", "Bahrian", "BAHRAIN", "BAHRIAN", "巴林"),
            new("103", "孟加拉国", "Bangladesh", "BANGLADESH", "孟加拉", "孟加拉国"),
            new("104", "不丹", "Bhutan", "BHUTAN", "不丹"),
            new("105", "文莱", "Brunei", "BRUNEI", "文莱"),
            new("106", "缅甸", "Myanmar", "MYANMAR", "BURMA", "缅甸"),
            new("107", "柬埔寨", "Cambodia", "CAMBODIA", "柬埔寨"),
            new("108", "塞浦路斯", "Cyprus", "CYPRUS", "塞浦路斯"),
            new("109", "朝鲜", "Korea,DPR", "KOREADPR", "DPRK", "朝鲜"),
            new("110", "香港", "Hong Kong", "HONGKONG", "香港"),
            new("111", "印度", "India", "INDIA", "印度"),
            new("112", "印度尼西亚", "Indonesia", "INDONESIA", "印尼", "印度尼西亚"),
            new("113", "伊朗", "Iran", "IRAN", "伊朗"),
            new("114", "伊拉克", "Iraq", "IRAQ", "伊拉克"),
            new("115", "以色列", "Israel", "ISRAEL", "以色列"),
            new("116", "日本", "Japan", "JAPAN", "日本"),
            new("117", "约旦", "Jordan", "JORDAN", "约旦"),
            new("118", "科威特", "Kuwait", "KUWAIT", "科威特"),
            new("119", "老挝", "Lao PDR", "LAOPDR", "LAOS", "老挝"),
            new("120", "黎巴嫩", "Lebanon", "LEBANON", "黎巴嫩"),
            new("121", "澳门", "Macao", "MACAO", "MACAU", "澳门"),
            new("122", "马来西亚", "Malaysia", "MALAYSIA", "马来西亚"),
            new("123", "马尔代夫", "Maldives", "MALDIVES", "马尔代夫"),
            new("124", "蒙古", "Mongolia", "MONGOLIA", "蒙古"),
            new("125", "尼泊尔", "Nepal", "NEPAL", "尼泊尔"),
            new("126", "阿曼", "Oman", "OMAN", "阿曼"),
            new("127", "巴基斯坦", "Pakistan", "PAKISTAN", "巴基斯坦"),
            new("128", "卡塔尔", "Qatar", "QATAR", "卡塔尔"),
            new("129", "沙特阿拉伯", "Saudi Arabia", "SAUDIARABIA", "沙特", "沙特阿拉伯"),
            new("130", "新加坡", "Singapore", "SINGAPORE", "新加坡"),
            new("131", "韩国", "Korea,Rep.", "KOREAREP", "SOUTHKOREA", "韩国"),
            new("132", "斯里兰卡", "Sri Lanka", "SRILANKA", "斯里兰卡"),
            new("133", "叙利亚", "Syria", "SYRIA", "叙利亚"),
            new("134", "泰国", "Thailand", "THAILAND", "泰国"),
            new("135", "土耳其", "Türkiye", "TURKIYE", "TURKEY", "土耳其"),
            new("136", "阿联酋", "United Arab Emirates", "UNITEDARABEMIRATES", "UAE", "阿联酋"),
            new("137", "也门", "Yemen", "YEMEN", "也门"),
            new("138", "越南", "Viet Nam", "VIETNAM", "VIETNAM", "越南"),
            new("142", "中国", "China", "CHINA", "CN", "CHN", "中国"),
            new("143", "台澎金马关税区", "Taiwan, Prov.of China", "TAIWANPROVOFCHINA", "TAIWAN", "台湾", "中国台湾"),
            new("201", "阿尔及利亚", "Algeria", "ALGERIA", "阿尔及利亚"),
            new("202", "安哥拉", "Angola", "ANGOLA", "安哥拉"),
            new("203", "贝宁", "Benin", "BENIN", "贝宁"),
            new("204", "博茨瓦纳", "Botswana", "BOTSWANA", "博茨瓦纳"),
            new("205", "布隆迪", "Burundi", "BURUNDI", "布隆迪"),
            new("206", "喀麦隆", "Cameroon", "CAMEROON", "喀麦隆"),
            new("207", "加那利群岛", "Canary Is.", "CANARYIS", "加那利群岛"),
            new("208", "佛得角", "Cape Verde", "CAPEVERDE", "佛得角"),
            new("209", "中非", "Central African Rep.", "CENTRALAFRICANREP", "中非"),
            new("210", "乍得", "Chad", "CHAD", "乍得"),
            new("211", "刚果", "Congo", "CONGO", "刚果"),
            new("212", "吉布提", "Djibouti", "DJIBOUTI", "吉布提"),
            new("213", "埃及", "Egypt", "EGYPT", "埃及"),
            new("214", "赤道几内亚", "Equatorial Guinea", "EQUATORIALGUINEA", "赤道几内亚"),
            new("215", "埃塞俄比亚", "Ethiopia", "ETHIOPIA", "埃塞俄比亚"),
            new("216", "加蓬", "Gabon", "GABON", "加蓬"),
            new("217", "冈比亚", "Gambia", "GAMBIA", "冈比亚"),
            new("218", "加纳", "Ghana", "GHANA", "加纳"),
            new("219", "几内亚", "Guinea", "GUINEA", "几内亚"),
            new("220", "几内亚比绍", "Guinea-Bissau", "GUINEABISSAU", "几内亚比绍"),
            new("221", "科特迪瓦", "Cote d'Ivoire", "COTEDIVOIRE", "IVORYCOAST", "科特迪瓦"),
            new("222", "肯尼亚", "Kenya", "KENYA", "肯尼亚"),
            new("223", "利比里亚", "Liberia", "LIBERIA", "利比里亚"),
            new("224", "利比亚", "Libya", "LIBYA", "利比亚"),
            new("225", "马达加斯加", "Madagascar", "MADAGASCAR", "马达加斯加"),
            new("226", "马拉维", "Malawi", "MALAWI", "马拉维"),
            new("227", "马里", "Mali", "MALI", "马里"),
            new("228", "毛里塔尼亚", "Mauritania", "MAURITANIA", "毛里塔尼亚"),
            new("229", "毛里求斯", "Mauritius", "MAURITIUS", "毛里求斯"),
            new("230", "摩洛哥", "Morocco", "MOROCCO", "摩洛哥"),
            new("231", "莫桑比克", "Mozambique", "MOZAMBIQUE", "莫桑比克"),
            new("232", "纳米比亚", "Namibia", "NAMIBIA", "纳米比亚"),
            new("233", "尼日尔", "Niger", "NIGER", "尼日尔"),
            new("234", "尼日利亚", "Nigeria", "NIGERIA", "尼日利亚"),
            new("235", "留尼汪", "Reunion", "REUNION", "留尼汪"),
            new("236", "卢旺达", "Rwanda", "RWANDA", "卢旺达"),
            new("237", "圣多美和普林西比", "Sao Tome and Principe", "SAOTOMEANDPRINCIPE", "圣多美和普林西比"),
            new("238", "塞内加尔", "Senegal", "SENEGAL", "塞内加尔"),
            new("239", "塞舌尔", "Seychelles", "SEYCHELLES", "塞舌尔"),
            new("240", "塞拉利昂", "Sierra Leone", "SIERRALEONE", "塞拉利昂"),
            new("241", "索马里", "Somalia", "SOMALIA", "索马里"),
            new("242", "南非", "South Africa", "SOUTHAFRICA", "南非"),
            new("243", "津巴布韦", "Zimbabwe", "ZIMBABWE", "津巴布韦"),
            new("244", "西撒哈拉", "Western Sahara", "WESTERNSAHARA", "西撒哈拉"),
            new("245", "乌干达", "Uganda", "UGANDA", "乌干达"),
            new("246", "坦桑尼亚", "Tanzania", "TANZANIA", "坦桑尼亚"),
            new("247", "赞比亚", "Zambia", "ZAMBIA", "赞比亚"),
            new("248", "科摩罗", "Comoros", "COMOROS", "科摩罗"),
            new("249", "马约特", "Mayotte", "MAYOTTE", "马约特"),
            new("250", "莱索托", "Lesotho", "LESOTHO", "莱索托"),
            new("251", "埃里特里亚", "Eritrea", "ERITREA", "埃里特里亚"),
            new("252", "斯威士兰", "Eswatini", "ESWATINI", "SWAZILAND", "斯威士兰"),
            new("253", "苏丹", "Sudan", "SUDAN", "苏丹"),
            new("254", "刚果民主共和国", "Dem. Rep. of the Congo", "DEMREPOFTHECONGO", "DRC", "刚果金"),
            new("255", "突尼斯", "Tunisia", "TUNISIA", "突尼斯"),
            new("256", "圣赫勒拿", "St.Helena", "STHELENA", "圣赫勒拿"),
            new("257", "阿森松", "Ascension", "ASCENSION", "阿森松"),
            new("258", "特里斯坦-达库尼亚群岛", "Tristan da Cunha", "TRISTANDACUNHA", "特里斯坦-达库尼亚群岛"),
            new("260", "南苏丹共和国", "Republic of South Sudan", "REPUBLICOFSOUTHSUDAN", "南苏丹"),
            new("301", "比利时", "Belgium", "BELGIUM", "比利时"),
            new("302", "丹麦", "Denmark", "DENMARK", "丹麦"),
            new("303", "英国", "United Kingdom", "UNITEDKINGDOM", "UK", "GB", "英国"),
            new("304", "德国", "Germany", "GERMANY", "德国"),
            new("305", "法国", "France", "FRANCE", "法国"),
            new("306", "爱尔兰", "Ireland", "IRELAND", "爱尔兰"),
            new("307", "意大利", "Italy", "ITALY", "意大利"),
            new("308", "卢森堡", "Luxembourg", "LUXEMBOURG", "卢森堡"),
            new("309", "荷兰", "Netherlands", "NETHERLANDS", "荷兰"),
            new("310", "希腊", "Greece", "GREECE", "希腊"),
            new("311", "葡萄牙", "Portugal", "PORTUGAL", "葡萄牙"),
            new("312", "西班牙", "Spain", "SPAIN", "西班牙"),
            new("313", "阿尔巴尼亚", "Albania", "ALBANIA", "阿尔巴尼亚"),
            new("314", "安道尔", "Andorra", "ANDORRA", "安道尔"),
            new("315", "奥地利", "Austria", "AUSTRIA", "奥地利"),
            new("316", "保加利亚", "Bulgaria", "BULGARIA", "保加利亚"),
            new("318", "芬兰", "Finland", "FINLAND", "芬兰"),
            new("320", "直布罗陀", "Gibraltar", "GIBRALTAR", "直布罗陀"),
            new("321", "匈牙利", "Hungary", "HUNGARY", "匈牙利"),
            new("322", "冰岛", "Iceland", "ICELAND", "冰岛"),
            new("323", "列支敦士登", "Liechtenstein", "LIECHTENSTEIN", "列支敦士登"),
            new("324", "马耳他", "Malta", "MALTA", "马耳他"),
            new("325", "摩纳哥", "Monaco", "MONACO", "摩纳哥"),
            new("326", "挪威", "Norway", "NORWAY", "挪威"),
            new("327", "波兰", "Poland", "POLAND", "波兰"),
            new("328", "罗马尼亚", "Romania", "ROMANIA", "罗马尼亚"),
            new("329", "圣马力诺", "San Marino", "SANMARINO", "圣马力诺"),
            new("330", "瑞典", "Sweden", "SWEDEN", "瑞典"),
            new("331", "瑞士", "Switzerland", "SWITZERLAND", "瑞士"),
            new("332", "爱沙尼亚", "Estonia", "ESTONIA", "爱沙尼亚"),
            new("333", "拉脱维亚", "Latvia", "LATVIA", "拉脱维亚"),
            new("334", "立陶宛", "Lithuania", "LITHUANIA", "立陶宛"),
            new("335", "白俄罗斯", "Belarus", "BELARUS", "白俄罗斯"),
            new("336", "摩尔多瓦", "Moldova", "MOLDOVA", "摩尔多瓦"),
            new("337", "俄罗斯联邦", "Russian Federation", "RUSSIANFEDERATION", "RUSSIA", "俄罗斯"),
            new("338", "乌克兰", "Ukraine", "UKRAINE", "乌克兰"),
            new("339", "波黑", "Bosnia and Herzegovina", "BOSNIAANDHERZEGOVINA", "波黑"),
            new("340", "克罗地亚", "Croatia", "CROATIA", "克罗地亚"),
            new("341", "斯洛文尼亚", "Slovenia", "SLOVENIA", "斯洛文尼亚"),
            new("343", "捷克", "Czech Rep.", "CZECHREP", "CZECHIA", "捷克"),
            new("344", "斯洛伐克", "Slovakia", "SLOVAKIA", "斯洛伐克"),
            new("345", "法罗群岛", "Faroe Is.", "FAROEIS", "法罗群岛"),
            new("346", "塞黑", "Serbia and Montenegro", "SERBIAANDMONTENEGRO", "塞黑"),
            new("347", "马其顿", "North Macedonia", "NORTHMACEDONIA", "MACEDONIA", "马其顿"),
            new("348", "塞尔维亚", "Serbia", "SERBIA", "塞尔维亚"),
            new("349", "黑山", "Montenegro", "MONTENEGRO", "黑山"),
            new("350", "格恩西岛", "Guernsey", "GUERNSEY", "根西岛", "格恩西岛"),
            new("351", "泽西岛", "Jersey", "JERSEY", "泽西岛"),
            new("352", "马恩岛", "Isle of Man", "ISLEOFMAN", "马恩岛"),
            new("353", "法罗群岛", "Faroe Islands", "FAROEISLANDS", "法罗群岛"),
            new("401", "安提瓜和巴布达", "Antigua and Barbuda", "ANTIGUAANDBARBUDA", "安提瓜和巴布达"),
            new("402", "阿根廷", "Argentina", "ARGENTINA", "阿根廷"),
            new("403", "阿鲁巴", "Aruba", "ARUBA", "阿鲁巴"),
            new("404", "巴哈马", "Bahamas", "BAHAMAS", "巴哈马"),
            new("405", "巴巴多斯", "Barbados", "BARBADOS", "巴巴多斯"),
            new("406", "伯利兹", "Belize", "BELIZE", "伯利兹"),
            new("407", "玻利维亚", "Bolivia", "BOLIVIA", "玻利维亚"),
            new("408", "博内尔岛、圣尤斯特歇斯和萨巴", "Bonaire, Sint Eustatius and Saba", "BONAIRESINTEUSTATIUSANDSABA", "BES", "博内尔"),
            new("409", "巴西", "Brazil", "BRAZIL", "巴西"),
            new("410", "开曼群岛", "Cayman Is.", "CAYMANIS", "开曼群岛"),
            new("411", "智利", "Chile", "CHILE", "智利"),
            new("412", "哥伦比亚", "Colombia", "COLOMBIA", "哥伦比亚"),
            new("413", "多米尼克", "Dominica", "DOMINICA", "多米尼克"),
            new("414", "哥斯达黎加", "Costa Rica", "COSTARICA", "哥斯达黎加"),
            new("415", "古巴", "Cuba", "CUBA", "古巴"),
            new("416", "多米尼加共和国", "Dominican Rep.", "DOMINICANREP", "多米尼加共和国"),
            new("417", "厄瓜多尔", "Ecuador", "ECUADOR", "厄瓜多尔"),
            new("418", "法属圭亚那", "French Guiana", "FRENCHGUIANA", "法属圭亚那"),
            new("419", "格林纳达", "Grenada", "GRENADA", "格林纳达"),
            new("420", "瓜德罗普", "Guadeloupe", "GUADELOUPE", "瓜德罗普"),
            new("421", "危地马拉", "Guatemala", "GUATEMALA", "危地马拉"),
            new("422", "圭亚那", "Guyana", "GUYANA", "圭亚那"),
            new("423", "海地", "Haiti", "HAITI", "海地"),
            new("424", "洪都拉斯", "Honduras", "HONDURAS", "洪都拉斯"),
            new("425", "牙买加", "Jamaica", "JAMAICA", "牙买加"),
            new("426", "马提尼克", "Martinique", "MARTINIQUE", "马提尼克"),
            new("427", "墨西哥", "Mexico", "MEXICO", "墨西哥"),
            new("428", "蒙特塞拉特", "Montserrat", "MONTSERRAT", "蒙特塞拉特"),
            new("429", "尼加拉瓜", "Nicaragua", "NICARAGUA", "尼加拉瓜"),
            new("430", "巴拿马", "Panama", "PANAMA", "巴拿马"),
            new("431", "巴拉圭", "Paraguay", "PARAGUAY", "巴拉圭"),
            new("432", "秘鲁", "Peru", "PERU", "秘鲁"),
            new("433", "波多黎各", "Puerto Rico", "PUERTORICO", "波多黎各"),
            new("434", "萨尔瓦多", "El Salvador", "ELSALVADOR", "萨尔瓦多"),
            new("435", "苏里南", "Suriname", "SURINAME", "苏里南"),
            new("436", "特立尼达和多巴哥", "Trinidad and Tobago", "TRINIDADANDTOBAGO", "特立尼达和多巴哥"),
            new("437", "乌拉圭", "Uruguay", "URUGUAY", "乌拉圭"),
            new("438", "圣文森特和格林纳丁斯", "St.Vincent and the Grenadines", "STVINCENTANDTHEGRENADINES", "圣文森特和格林纳丁斯"),
            new("439", "委内瑞拉", "Venezuela", "VENEZUELA", "委内瑞拉"),
            new("440", "圣卢西亚", "St.Lucia", "STLUCIA", "圣卢西亚"),
            new("441", "圣基茨和尼维斯", "St.Kitts and Nevis", "STKITTSANDNEVIS", "圣基茨和尼维斯"),
            new("442", "安圭拉", "Anguilla", "ANGUILLA", "安圭拉"),
            new("443", "圣马丁(荷属)", "Sint Maarten", "SINTMAARTEN", "圣马丁"),
            new("444", "库拉索", "Curacao", "CURACAO", "库拉索"),
            new("445", "荷属圣马丁", "Saint Martin", "SAINTMARTIN", "荷属圣马丁"),
            new("446", "圣巴泰勒米", "Saint Barthelemy", "SAINTBARTHELEMY", "圣巴泰勒米"),
            new("447", "特克斯和凯科斯群岛", "Turks and Caicos Is.", "TURKSANDCAICOSIS", "特克斯和凯科斯群岛"),
            new("448", "英属维尔京群岛", "British Virgin Is.", "BRITISHVIRGINIS", "英属维尔京群岛"),
            new("449", "荷属安的列斯", "Netherlands Antilles", "NETHERLANDSANTILLES", "荷属安的列斯"),
            new("450", "格陵兰", "Greenland", "GREENLAND", "格陵兰"),
            new("451", "法属圣马丁", "Saint Martin (French part)", "SAINTMARTINFRENCHPART", "法属圣马丁"),
            new("452", "百慕大", "Bermuda", "BERMUDA", "百慕大"),
            new("453", "圣皮埃尔和密克隆", "St.Pierre and Miquelon", "STPIERREANDMIQUELON", "圣皮埃尔和密克隆"),
            new("454", "法属圣巴泰勒米", "Saint-Barthelemy", "SAINTBARTHELEMY", "法属圣巴泰勒米"),
            new("455", "中美洲其他国家(地区)", "Oth. C./S. America nes", "OTHCSAMERICANES", "中美洲其他国家", "南美洲其他国家"),
            new("501", "加拿大", "Canada", "CANADA", "加拿大"),
            new("502", "美国", "United States", "UNITEDSTATES", "USA", "US", "美国"),
            new("503", "澳大利亚", "Australia", "AUSTRALIA", "澳大利亚"),
            new("504", "新西兰", "New Zealand", "NEWZEALAND", "新西兰"),
            new("505", "巴布亚新几内亚", "Papua New Guinea", "PAPUANEWGUINEA", "巴布亚新几内亚"),
            new("506", "斐济", "Fiji", "FIJI", "斐济"),
            new("507", "所罗门群岛", "Solomon Is.", "SOLOMONIS", "所罗门群岛"),
            new("508", "瓦努阿图", "Vanuatu", "VANUATU", "瓦努阿图"),
            new("509", "库克群岛", "Cook Is.", "COOKIS", "库克群岛"),
            new("510", "萨摩亚", "Samoa", "SAMOA", "萨摩亚"),
            new("511", "基里巴斯", "Kiribati", "KIRIBATI", "基里巴斯"),
            new("512", "新喀里多尼亚", "New Caledonia", "NEWCALEDONIA", "新喀里多尼亚"),
            new("513", "法属波利尼西亚", "French Polynesia", "FRENCHPOLYNESIA", "法属波利尼西亚"),
            new("514", "图瓦卢", "Tuvalu", "TUVALU", "图瓦卢"),
            new("515", "关岛", "Guam", "GUAM", "关岛"),
            new("516", "瑙鲁", "Nauru", "NAURU", "瑙鲁"),
            new("517", "汤加", "Tonga", "TONGA", "汤加"),
            new("518", "美属萨摩亚", "American Samoa", "AMERICANSAMOA", "美属萨摩亚"),
            new("519", "北马里亚纳", "Northern Mariana Is.", "NORTHERNMARIANAIS", "北马里亚纳"),
            new("520", "密克罗尼西亚联邦", "Micronesia, Fs", "MICRONESIAFS", "密克罗尼西亚联邦"),
            new("621", "马绍尔群岛", "Marshall Islands", "MARSHALLISLANDS", "马绍尔群岛"),
            new("622", "帕劳", "Palau", "PALAU", "帕劳"),
            new("623", "法属波利尼西亚", "French Polynesia", "FRENCHPOLYNESIA", "法属波利尼西亚"),
            new("625", "瓦利斯和浮图纳", "Wallis and Futuna", "WALLISANDFUTUNA", "瓦利斯和浮图纳"),
            new("699", "大洋洲其他国家(地区)", "Oth. Ocean. nes", "OTHOCEANNES", "大洋洲其他国家", "大洋洲其他地区"),
            new("701", "国(地)别不详", "Countries(reg.) unknown", "COUNTRIESREGUNKNOWN", "不详"),
            new("702", "联合国及机构和国际组织", "UN and oth. int'l  org.", "UNANDOTHINTLORG", "联合国及机构和国际组织"),
            new("999", "中性包装原产国别", "Conutries of Neutral Package", "CONUTRIESOFNEUTRALPACKAGE", "中性包装原产国别")
        ];

        private static readonly AcdTradeModeCatalogEntry[] FallbackAcdTradeModeCatalog =
        [
            new("0110", "一般贸易", "一般贸易", "一般贸易"),
            new("0130", "易货贸易", "易货贸易", "易货贸易"),
            new("0139", "旅游购物商品", "用于旅游者五万美元以下的出口小批量订货", "旅游购物商品"),
            new("0214", "来料加工", "来料加工装配贸易进口料件及加工出口货物", "来料加工"),
            new("0314", "加工专用油", "国营贸易企业代理来料加工企业进口柴油", "加工专用油"),
            new("0414", "加工贸易进口设备", "加工贸易项下进口设备", "加工贸易进口设备"),
            new("0615", "进料对口", "进料加工对口合同项下的进口料件及加工出口货物", "进料对口", "进料加工"),
            new("0715", "三来一补", "三来一补", "三来一补"),
            new("1215", "保税工厂", "保税工厂", "保税工厂"),
            new("2215", "来料深加工", "来料深加工结转货物", "来料深加工"),
            new("2225", "来料余料结转", "来料加工余料结转", "来料余料结转"),
            new("4019", "海关特殊监管区域物流货物", "海关特殊监管区域物流货物", "海关特殊监管区域物流货物"),
            new("5019", "保税物流中心货物", "保税物流中心货物", "保税物流中心货物"),
            new("6033", "物流中心进出境货", "保税物流中心与境外之间进出仓储货物", "物流中心进出境货"),
            new("9600", "内贸货物跨境运输", "内贸货物跨境运输", "内贸货物跨境运输"),
            new("9739", "其他贸易", "其他贸易", "其他贸易"),
            new("9800", "租赁征税", "租赁期一年及以上的租赁贸易货物的租金", "租赁征税"),
            new("9839", "留赠转卖物品", "外交机构转售境内或国际活动留赠放弃特批货", "留赠转卖物品"),
            new("9900", "其他", "其他", "其他")
        ];

        private static readonly TransportModeCatalogEntry[] FallbackTransportModeCatalog =
        [
            new("BY SEA", "SEA", "OCEAN", "VESSEL", "SHIP", "海运", "船运", "水运"),
            new("BY AIR", "AIR", "AIRPLANE", "FLIGHT", "空运"),
            new("BY RAIL", "RAIL", "TRAIN", "铁运", "铁路"),
            new("BY TRUCK", "TRUCK", "ROAD", "汽运", "陆运", "公路"),
            new("BY POST", "MAIL", "POST", "邮寄", "邮政")
        ];

        private static readonly PortCatalogEntry[] FallbackPortCatalog =
        [
            new("NINGBO", "宁波", "NINGBOCHINA", "NINGBO PORT"),
            new("SHANGHAI", "上海", "SHANGHAICHINA", "SHANGHAI PORT"),
            new("QINGDAO", "青岛", "QINGDAOCHINA", "QINGDAO PORT"),
            new("XIAMEN", "厦门", "XIAMENCHINA", "XIAMEN PORT"),
            new("SHENZHEN", "深圳", "YANTIAN", "SHEKOU", "SHENZHENCHINA"),
            new("GUANGZHOU", "广州", "NANSHA", "GUANGZHOUCHINA"),
            new("TIANJIN", "天津", "TIANJINCHINA"),
            new("DALIAN", "大连", "DALIANCHINA"),
            new("JAKARTA", "雅加达", "TANJUNGPRIOK"),
            new("SINGAPORE", "新加坡"),
            new("BUSAN", "釜山", "PUSAN"),
            new("TOKYO", "东京"),
            new("OSAKA", "大阪"),
            new("LOS ANGELES", "洛杉矶", "LOSANGELES"),
            new("LONG BEACH", "长滩", "LONGBEACH"),
            new("NEW YORK", "纽约", "NEWYORK"),
            new("HAMBURG", "汉堡"),
            new("ROTTERDAM", "鹿特丹"),
            new("DUBAI", "迪拜", "JEBELALI", "JEBEL ALI"),
            new("HO CHI MINH", "胡志明", "HOCHIMINH", "SAIGON"),
            new("BANGKOK", "曼谷", "LAEMCHABANG", "LAEM CHABANG"),
            new("MANILA", "马尼拉"),
            new("HAIPHONG", "海防", "HAI PHONG")
        ];

        static SingleWindowFieldMapperHelpers()
        {
            ReloadReferenceCatalog();
        }
    }
}
