pub fn label(key: &str) -> String {
    if let Some(number) = key.strip_prefix("spare") {
        return format!("备用 {number}");
    }
    match key {
        "name" => "名称",
        "code" => "代码",
        "description" => "说明",
        "notes" | "note" => "备注 / 原因",
        "isActive" => "启用",
        "status" => "状态",
        "type" => "类型",
        "invoiceNo" => "发票号",
        "invoiceDate" => "发票日期",
        "contractNo" => "合同号",
        "shipmentDate" => "装运日期",
        "currency" => "币种",
        "totalAmount" => "总金额",
        "paymentTerms" => "付款条件",
        "customerNameEN" => "客户英文名称",
        "displayName" => "显示名称",
        "customerNameCN" => "客户中文名称",
        "exporterNameEN" => "出口商英文名称",
        "exporterNameCN" => "出口商中文名称",
        "customerId" | "crmCustomerId" => "客户",
        "supplierId" | "supplierCompanyId" => "供应商",
        "productId" => "商品",
        "exporterId" => "出口商",
        "payeeId" => "收款人",
        "crmContactId" => "客户联系人",
        "addressEN" => "英文地址",
        "addressCN" => "中文地址",
        "customerAddressEN" => "客户英文地址",
        "exporterAddressEN" => "出口商英文地址",
        "contactPerson" => "联系人",
        "phone" => "电话",
        "email" => "邮箱",
        "website" => "网站",
        "country" | "countryRegion" => "国家 / 地区",
        "category" => "分类",
        "source" => "来源",
        "bankName" => "银行名称",
        "accountNo" | "bankAccount" => "银行账号",
        "rmbAccount" => "人民币账号",
        "usdAccount" => "美元账号",
        "swiftCode" => "SWIFT 代码",
        "creditCode" => "统一社会信用代码",
        "customsCode" => "海关编码",
        "taxId" => "税号",
        "notifyPartyName" => "通知人名称",
        "notifyPartyAddress" => "通知人地址",
        "notifyPartyMode" => "通知人方式",
        "mainProducts" => "主营产品",
        "linkedDocumentCustomerId" => "关联制单客户",
        "isPrimary" => "主要联系人",
        "jobTitle" => "岗位 / 职务",
        "mobile" => "手机",
        "wechat" => "微信",
        "whatsApp" => "WhatsApp",
        "title" => "主题 / 名称",
        "summary" => "沟通摘要",
        "nextAction" => "下一步动作",
        "followedUpAt" => "跟进时间",
        "nextFollowUpAt" => "下次跟进时间",
        "quotationNo" => "报价单号",
        "estimatedAmount" => "预计金额",
        "probabilityPercent" => "成交概率 (%)",
        "expectedCloseDate" => "预计成交日期",
        "changeNote" => "变更说明",
        "nextStage" => "目标销售阶段",
        "styleNo" => "款号",
        "styleName" => "英文品名",
        "styleNameCN" => "中文品名",
        "brand" => "品牌",
        "fabricComposition" => "成分",
        "hsCode" => "HS 编码",
        "origin" => "原产国",
        "supplierStyleNo" => "供应商款号",
        "unitPrice" => "单价",
        "totalPrice" => "金额",
        "quantity" => "数量",
        "unit" => "单位",
        "unitEN" => "英文单位",
        "unitCN" => "中文单位",
        "nameEN" => "英文名称",
        "nameCN" => "中文名称",
        "cartons" => "箱数",
        "gwTotal" => "总毛重",
        "nwTotal" => "总净重",
        "volume" => "体积 (m³)",
        "assessmentDate" => "评价日期",
        "assessmentKind" => "评价类型",
        "qualityScore" => "质量评分",
        "deliveryScore" => "交期评分",
        "serviceScore" => "服务评分",
        "priceScore" => "价格评分",
        "conclusion" => "评价结论",
        "voucherNo" => "凭证号",
        "quantityUnit" => "数量单位",
        "tradeMethod" => "贸易方式",
        "taxRebateRate" => "退税率",
        "department" => "部门",
        "project" => "项目",
        "usdAmount" => "美元金额",
        "cnyAmount" => "人民币金额",
        "paymentMethod" => "付款方式",
        "payeeName" => "收款人",
        "payerName" => "付款人",
        "paymentDate" => "付款日期",
        "goodsName" => "货物名称",
        "shipmentCountry" => "目的国",
        "receiptDate" => "收款日期",
        "travelExpense" => "差旅费",
        "businessEntertainmentExpense" => "业务招待费",
        "telephoneExpense" => "电话费",
        "officeExpense" => "办公费",
        "repairExpense" => "修理费",
        "freightMiscExpense" => "运杂费",
        "inspectionExpense" => "检验费",
        "otherExpense" => "其他费用",
        "employeeNumber" => "工号",
        "fullName" => "姓名",
        "departmentId" => "所属部门",
        "companyCode" | "companyScope" => "所属公司",
        "parentCode" => "上级部门",
        "managerEmployeeId" => "部门负责人",
        "employeeId" => "登记人员",
        "employmentType" => "用工类型",
        "hireDate" => "入职日期",
        "onProbation" => "试用期",
        "probationEndsOn" => "试用期结束",
        "contractEndsOn" => "合同到期日",
        "effectiveDate" => "生效日期",
        "profile" => "个人资料",
        "registration" => "初始登记修正",
        "workEmail" => "工作邮箱",
        "workPhone" => "工作电话",
        "workLocation" => "办公地点",
        "personalPhone" => "私人手机",
        "emergencyContact" => "紧急联系人",
        "emergencyPhone" => "紧急联系电话",
        "identityNumber" => "身份证号码",
        "identityAuthority" => "签发机关",
        "registeredAddress" => "身份证住址",
        "identityValidFrom" => "有效期起",
        "identityValidUntil" => "有效期止",
        "identityLongTerm" => "长期有效",
        "location" => "位置",
        "equipment" => "设备",
        "capacity" => "可容纳人数",
        "maximumBookingHours" => "最长预约 (小时)",
        "advanceBookingDays" => "可提前预约 (天)",
        "requiresKey" => "需要钥匙交接",
        "meetingRoomId" => "会议室",
        "attendeeCount" => "参会人数",
        "startsAt" => "开始时间",
        "endsAt" => "结束时间",
        "officeSupplyId" => "办公物品",
        "purpose" => "用途",
        "returnDueDate" => "应还日期",
        "isReturnable" => "需要归还",
        "minimumStock" => "最低库存",
        "username" => "登录账号",
        "role" => "角色",
        "resetPassword" => "设置 / 重置密码",
        "permissionTemplateId" => "权限方案",
        "grants" => "授权条目",
        "resourceKey" => "资源",
        "action" => "操作",
        "dataScope" => "数据范围",
        "targetStatus" => "目标状态",
        "reportType" => "报表类型",
        "contentHtml" => "模板内容",
        "subject" => "邮件主题",
        "bodyHtml" => "邮件正文",
        "containerType" => "柜型",
        "container" => "集装箱尺寸",
        "rules" => "装载规则",
        "cargoItems" => "货物清单",
        "length" => "长",
        "width" => "宽",
        "height" => "高",
        "weight" => "重量",
        "maxWeight" => "最大载重",
        "elements" => "申报要素",
        "supervisionConditions" => "监管条件",
        "inspectionCategory" => "检验检疫类别",
        "rebateRate" => "退税率",
        "detailUrl" => "资料地址",
        "sourceName" => "资料来源",
        "effectiveYear" => "生效年份",
        "normalTariffRate" => "普通税率",
        "preferentialTariffRate" => "最惠国税率",
        "exportTariffRate" => "出口税率",
        "consumptionTaxRate" => "消费税率",
        "valueAddedTaxRate" => "增值税率",
        "purchasePrice" => "采购单价",
        "purchaseTotal" => "采购金额",
        "taxRefundAmount" => "退税金额",
        "pcsPerCtn" => "每箱数量",
        "ctnUnitEN" => "英文包装单位",
        "ctnUnitCN" => "中文包装单位",
        "gwPerCtn" => "每箱毛重",
        "nwPerCtn" => "每箱净重",
        "priceCalculationMode" => "计价方式",
        "supervisionMode" => "监管方式",
        "customsBrokerName" => "报关行名称",
        "customsBrokerCode" => "报关行代码",
        "issuingBank" => "开证行",
        "letterOfCreditContent" => "信用证内容",
        "exporterAddressCN" => "出口商中文地址",
        "exporterCreditCode" => "出口商信用代码",
        "exporterCustomsCode" => "出口商海关编码",
        "system" => "常规与存储",
        "reportTemplateDefaults" => "默认报表",
        "batchExport" => "批量导出",
        "paymentTemplates" => "付款模板",
        "excelImport" => "Excel 导入",
        "excelImportSchemes" => "Excel 导入方案",
        "exchangeRate" => "汇率",
        "webDav" => "云备份",
        "ai" => "智能辅助",
        "singleWindow" => "单一窗口",
        _ => key,
    }
    .into()
}
pub fn internal(key: &str) -> bool {
    matches!(
        key,
        "id" | "invoiceId"
            | "ownerUserId"
            | "rowVersion"
            | "versionNumber"
            | "expectedVersion"
            | "requestKey"
            | "operationId"
            | "createdAt"
            | "updatedAt"
            | "normalizedCode"
            | "revision"
            | "expectedRevision"
            | "customFieldsJson"
    )
}
