using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

var options = GeneratorOptions.Parse(args);
var document = await OfficialOpenApiDocumentLoader.LoadAsync(options.BaseUrl);
string generated = TypeScriptClientGenerator.Generate(document);
string? outputDirectory = Path.GetDirectoryName(options.OutputPath);
if (!string.IsNullOrWhiteSpace(outputDirectory))
{
    Directory.CreateDirectory(outputDirectory);
}

File.WriteAllText(options.OutputPath, generated, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated TypeScript API client: {options.OutputPath}");

internal static partial class TypeScriptClientGenerator
{
    private static readonly string[] HttpMethods = ["get", "post", "put", "delete", "patch"];

    public static string Generate(JsonObject document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var schemas = GetObject(document, "components", "schemas");
        var operations = DiscoverOperations(document);
        var builder = new StringBuilder();

        EmitHeader(builder);
        var schemaTypeNames = GetSchemaTypeNames(schemas);
        EmitSchemaTypes(builder, schemas);
        EmitMissingReferencedSchemaAliases(builder, document, schemaTypeNames);
        EmitOperationRequestTypes(builder, operations);
        EmitClient(builder, operations);

        return builder.ToString();
    }

    private static void EmitHeader(StringBuilder builder)
    {
        builder.AppendLine("/* eslint-disable */");
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by tools/ExportDocManager.ApiClientGenerator from ExportDocManager.Api OpenAPI metadata.");
        builder.AppendLine("// Do not edit this file by hand. Run scripts/generate-api-client.ps1 instead.");
        builder.AppendLine();
    }

    private static void EmitSchemaTypes(StringBuilder builder, JsonObject? schemas)
    {
        if (schemas == null)
        {
            return;
        }

        foreach (var schema in schemas.OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            string typeName = ToTypeName(schema.Key);
            if (schema.Value is not JsonObject schemaObject)
            {
                builder.AppendLine($"export type {typeName} = unknown;");
                builder.AppendLine();
                continue;
            }

            if (TryGetEnumType(schemaObject, out string enumType))
            {
                builder.AppendLine($"export type {typeName} = {enumType};");
                builder.AppendLine();
                continue;
            }

            if (TryGetProperties(schemaObject, out var properties))
            {
                var required = GetRequiredProperties(schemaObject);
                builder.AppendLine($"export interface {typeName} {{");
                foreach (var property in properties.OrderBy(item => item.Key, StringComparer.Ordinal))
                {
                    string optional = required.Contains(property.Key) ? string.Empty : "?";
                    string propertyType = SchemaToType(property.Value as JsonObject);
                    builder.AppendLine($"  {FormatPropertyName(property.Key)}{optional}: {propertyType};");
                }

                builder.AppendLine("}");
                builder.AppendLine();
                continue;
            }

            builder.AppendLine($"export type {typeName} = {SchemaToType(schemaObject)};");
            builder.AppendLine();
        }
    }

    private static void EmitMissingReferencedSchemaAliases(
        StringBuilder builder,
        JsonObject document,
        HashSet<string> schemaTypeNames)
    {
        var referencedTypeNames = new SortedSet<string>(StringComparer.Ordinal);
        CollectReferencedTypeNames(document, referencedTypeNames);

        foreach (string typeName in referencedTypeNames)
        {
            if (schemaTypeNames.Contains(typeName))
            {
                continue;
            }

            builder.AppendLine($"export type {typeName} = Record<string, unknown>;");
            builder.AppendLine();
        }
    }

    private static void EmitOperationRequestTypes(StringBuilder builder, IReadOnlyList<ApiOperation> operations)
    {
        foreach (var operation in operations)
        {
            if (!operation.HasRequestType)
            {
                continue;
            }

            builder.AppendLine($"export interface {operation.RequestTypeName} {{");
            foreach (var parameter in operation.PathParameters
                         .Concat(operation.QueryParameters)
                         .Concat(operation.HeaderParameters))
            {
                string optional = parameter.Required ? string.Empty : "?";
                builder.AppendLine($"  {FormatPropertyName(parameter.Name)}{optional}: {parameter.TypeName};");
            }

            if (!string.IsNullOrWhiteSpace(operation.BodyTypeName))
            {
                string optional = operation.BodyRequired ? string.Empty : "?";
                builder.AppendLine($"  body{optional}: {operation.BodyTypeName};");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static void EmitClient(StringBuilder builder, IReadOnlyList<ApiOperation> operations)
    {
        builder.AppendLine("export type AccessTokenProvider = string | ((signal?: AbortSignal) => string | undefined | Promise<string | undefined>);");
        builder.AppendLine("export type ApiRequestInit = RequestInit & { timeoutMs?: number };");
        builder.AppendLine("type QueryValue = string | number | boolean | null | undefined;");
        builder.AppendLine("const desktopAccessTokenHeaderName = \"X-ExportDocManager-Desktop-Token\";");
        builder.AppendLine();
        builder.AppendLine("export interface ApiClientOptions {");
        builder.AppendLine("  baseUrl: string;");
        builder.AppendLine("  accessToken?: AccessTokenProvider;");
        builder.AppendLine("  desktopAccessToken?: AccessTokenProvider;");
        builder.AppendLine("  defaultTimeoutMs?: number;");
        builder.AppendLine("  fetch?: typeof globalThis.fetch;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export class ApiError extends Error {");
        builder.AppendLine("  constructor(");
        builder.AppendLine("    public readonly status: number,");
        builder.AppendLine("    public readonly statusText: string,");
        builder.AppendLine("    public readonly responseText: string,");
        builder.AppendLine("  ) {");
        builder.AppendLine("    super(`API request failed with status ${status} ${statusText}`);");
        builder.AppendLine("    this.name = \"ApiError\";");
        builder.AppendLine("  }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export function createExportDocManagerApiClient(options: ApiClientOptions): ExportDocManagerApiClient {");
        builder.AppendLine("  return new ExportDocManagerApiClient(options);");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export class ExportDocManagerApiClient {");
        builder.AppendLine("  private readonly baseUrl: string;");
        builder.AppendLine("  private readonly accessToken?: AccessTokenProvider;");
        builder.AppendLine("  private readonly desktopAccessToken?: AccessTokenProvider;");
        builder.AppendLine("  private readonly defaultTimeoutMs: number;");
        builder.AppendLine("  private readonly fetchImpl: typeof globalThis.fetch;");
        builder.AppendLine();
        builder.AppendLine("  constructor(options: ApiClientOptions) {");
        builder.AppendLine("    this.baseUrl = `${options.baseUrl.replace(/\\/+$/, \"\")}/`;");
        builder.AppendLine("    this.accessToken = options.accessToken;");
        builder.AppendLine("    this.desktopAccessToken = options.desktopAccessToken;");
        builder.AppendLine("    this.defaultTimeoutMs = normalizeTimeout(options.defaultTimeoutMs ?? 60_000);");
        builder.AppendLine("    if (typeof options.fetch === \"function\") {");
        builder.AppendLine("      this.fetchImpl = options.fetch;");
        builder.AppendLine("    } else if (typeof globalThis.fetch === \"function\") {");
        builder.AppendLine("      this.fetchImpl = globalThis.fetch.bind(globalThis);");
        builder.AppendLine("    } else {");
        builder.AppendLine("      throw new Error(\"A fetch implementation is required to use ExportDocManagerApiClient.\");");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  public resolveUrl(path: string): string {");
        builder.AppendLine("    return new URL(path, this.baseUrl).toString();");
        builder.AppendLine("  }");
        builder.AppendLine();

        foreach (var operation in operations)
        {
            EmitClientMethod(builder, operation);
        }

        builder.AppendLine("  private async resolveAccessToken(signal?: AbortSignal): Promise<string | undefined> {");
        builder.AppendLine("    const provider = this.accessToken;");
        builder.AppendLine("    if (typeof provider === \"function\") {");
        builder.AppendLine("      throwIfAborted(signal);");
        builder.AppendLine("      return awaitWithSignal(Promise.resolve().then(() => provider(signal)), signal);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    return provider;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  private async resolveDesktopAccessToken(signal?: AbortSignal): Promise<string | undefined> {");
        builder.AppendLine("    const provider = this.desktopAccessToken;");
        builder.AppendLine("    if (typeof provider === \"function\") {");
        builder.AppendLine("      throwIfAborted(signal);");
        builder.AppendLine("      return awaitWithSignal(Promise.resolve().then(() => provider(signal)), signal);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    return provider;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  private async request<T>(");
        builder.AppendLine("    method: string,");
        builder.AppendLine("    path: string,");
        builder.AppendLine("    options: { query?: Record<string, QueryValue>; body?: unknown; init?: ApiRequestInit } = {},");
        builder.AppendLine("  ): Promise<T> {");
        builder.AppendLine("    const { headers: initHeaders, body: _ignoredBody, signal: callerSignal, timeoutMs, ...restInit } = options.init ?? {};");
        builder.AppendLine("    const timeout = createRequestTimeout(callerSignal, timeoutMs ?? this.defaultTimeoutMs);");
        builder.AppendLine("    try {");
        builder.AppendLine("      const headers = new Headers(initHeaders);");
        builder.AppendLine("      const isFormDataBody = typeof FormData !== \"undefined\" && options.body instanceof FormData;");
        builder.AppendLine("      const isBlobBody = typeof Blob !== \"undefined\" && options.body instanceof Blob;");
        builder.AppendLine("      if (!headers.has(\"Accept\")) {");
        builder.AppendLine("        headers.set(\"Accept\", \"application/json\");");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      if (options.body !== undefined && !headers.has(\"Content-Type\")) {");
        builder.AppendLine("        if (isBlobBody) {");
        builder.AppendLine("          headers.set(\"Content-Type\", \"application/octet-stream\");");
        builder.AppendLine("        } else if (!isFormDataBody) {");
        builder.AppendLine("          headers.set(\"Content-Type\", \"application/json\");");
        builder.AppendLine("        }");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      const requestSignal = timeout.signal;");
        builder.AppendLine("      const desktopToken = await this.resolveDesktopAccessToken(requestSignal);");
        builder.AppendLine("      if (desktopToken && !headers.has(desktopAccessTokenHeaderName)) {");
        builder.AppendLine("        headers.set(desktopAccessTokenHeaderName, desktopToken);");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      const token = await this.resolveAccessToken(requestSignal);");
        builder.AppendLine("      if (token && !headers.has(\"Authorization\")) {");
        builder.AppendLine("        headers.set(\"Authorization\", `Bearer ${token}`);");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      const relativePath = appendQuery(path, options.query).replace(/^\\/+/, \"\");");
        builder.AppendLine("      const url = new URL(relativePath, this.baseUrl);");
        builder.AppendLine("      const requestInit: RequestInit = { ...restInit, method, headers, signal: requestSignal };");
        builder.AppendLine("      if (options.body !== undefined) {");
        builder.AppendLine("        requestInit.body = isFormDataBody || isBlobBody ? options.body as BodyInit : JSON.stringify(options.body);");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      throwIfAborted(requestSignal);");
        builder.AppendLine("      const response = await this.fetchImpl(url, requestInit);");
        builder.AppendLine("      const contentType = response.headers.get(\"content-type\") ?? \"\";");
        builder.AppendLine("      const contentDisposition = response.headers.get(\"content-disposition\") ?? \"\";");
        builder.AppendLine("      const isBinaryResponse = contentType.startsWith(\"image/\") || contentType.startsWith(\"audio/\") ||");
        builder.AppendLine("        contentType.startsWith(\"video/\") || contentType.includes(\"application/pdf\") ||");
        builder.AppendLine("        contentType.includes(\"application/octet-stream\") || contentDisposition.toLowerCase().includes(\"attachment\");");
        builder.AppendLine("      if (isBinaryResponse) {");
        builder.AppendLine("        if (!response.ok) {");
        builder.AppendLine("          throw new ApiError(response.status, response.statusText, await response.text());");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return await response.blob() as T;");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      const responseText = await response.text();");
        builder.AppendLine("      if (!response.ok) {");
        builder.AppendLine("        throw new ApiError(response.status, response.statusText, responseText);");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      if (!responseText) {");
        builder.AppendLine("        return undefined as T;");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      return (contentType.includes(\"application/json\") ? JSON.parse(responseText) : responseText) as T;");
        builder.AppendLine("    } finally {");
        builder.AppendLine("      timeout.dispose();");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function normalizeTimeout(value: number): number {");
        builder.AppendLine("  if (!Number.isFinite(value) || value < 0 || value > 60 * 60 * 1000) {");
        builder.AppendLine("    throw new RangeError(\"API request timeout must be between 0 and 3600000 milliseconds.\");");
        builder.AppendLine("  }");
        builder.AppendLine("  return Math.trunc(value);");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function throwIfAborted(signal: AbortSignal | null | undefined): void {");
        builder.AppendLine("  if (!signal?.aborted) return;");
        builder.AppendLine("  throw signal.reason ?? new DOMException(\"The operation was aborted.\", \"AbortError\");");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("async function awaitWithSignal<T>(value: PromiseLike<T> | T, signal: AbortSignal | null | undefined): Promise<T> {");
        builder.AppendLine("  throwIfAborted(signal);");
        builder.AppendLine("  if (!signal) return await value;");
        builder.AppendLine("  return await new Promise<T>((resolve, reject) => {");
        builder.AppendLine("    let settled = false;");
        builder.AppendLine("    const cleanup = () => signal.removeEventListener(\"abort\", onAbort);");
        builder.AppendLine("    const onAbort = () => {");
        builder.AppendLine("      if (settled) return;");
        builder.AppendLine("      settled = true;");
        builder.AppendLine("      cleanup();");
        builder.AppendLine("      reject(signal.reason ?? new DOMException(\"The operation was aborted.\", \"AbortError\"));");
        builder.AppendLine("    };");
        builder.AppendLine("    signal.addEventListener(\"abort\", onAbort, { once: true });");
        builder.AppendLine("    if (signal.aborted) onAbort();");
        builder.AppendLine("    Promise.resolve(value).then(result => {");
        builder.AppendLine("      if (settled) return;");
        builder.AppendLine("      settled = true;");
        builder.AppendLine("      cleanup();");
        builder.AppendLine("      resolve(result);");
        builder.AppendLine("    }, error => {");
        builder.AppendLine("      if (settled) return;");
        builder.AppendLine("      settled = true;");
        builder.AppendLine("      cleanup();");
        builder.AppendLine("      reject(error);");
        builder.AppendLine("    });");
        builder.AppendLine("  });");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function createRequestTimeout(callerSignal: AbortSignal | null | undefined, timeoutMs: number): { signal?: AbortSignal; dispose: () => void } {");
        builder.AppendLine("  const normalizedTimeout = normalizeTimeout(timeoutMs);");
        builder.AppendLine("  if (normalizedTimeout === 0) {");
        builder.AppendLine("    return { signal: callerSignal ?? undefined, dispose: () => undefined };");
        builder.AppendLine("  }");
        builder.AppendLine("  const timeoutController = new AbortController();");
        builder.AppendLine("  const timeoutId = setTimeout(() => timeoutController.abort(), normalizedTimeout);");
        builder.AppendLine("  const signals = [callerSignal, timeoutController.signal].filter((signal): signal is AbortSignal => Boolean(signal));");
        builder.AppendLine("  if (signals.length === 1) {");
        builder.AppendLine("    return { signal: signals[0], dispose: () => clearTimeout(timeoutId) };");
        builder.AppendLine("  }");
        builder.AppendLine("  const combinedController = new AbortController();");
        builder.AppendLine("  const abort = () => combinedController.abort();");
        builder.AppendLine("  for (const signal of signals) {");
        builder.AppendLine("    signal.addEventListener(\"abort\", abort, { once: true });");
        builder.AppendLine("    if (signal.aborted) abort();");
        builder.AppendLine("  }");
        builder.AppendLine("  return {");
        builder.AppendLine("    signal: combinedController.signal,");
        builder.AppendLine("    dispose: () => {");
        builder.AppendLine("      clearTimeout(timeoutId);");
        builder.AppendLine("      for (const signal of signals) signal.removeEventListener(\"abort\", abort);");
        builder.AppendLine("    },");
        builder.AppendLine("  };");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function appendQuery(path: string, query?: Record<string, QueryValue>): string {");
        builder.AppendLine("  const entries = Object.entries(query ?? {}).filter(([, value]) => value !== undefined && value !== null && value !== \"\");");
        builder.AppendLine("  if (entries.length === 0) {");
        builder.AppendLine("    return path;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  const search = new URLSearchParams();");
        builder.AppendLine("  for (const [key, value] of entries) {");
        builder.AppendLine("    search.append(key, String(value));");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  return `${path}?${search.toString()}`;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function encodePath(value: string | number | boolean): string {");
        builder.AppendLine("  return encodeURIComponent(String(value));");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function mergeHeaders(initHeaders: HeadersInit | undefined, values: Record<string, string | undefined>): Headers {");
        builder.AppendLine("  const headers = new Headers(initHeaders);");
        builder.AppendLine("  for (const [name, value] of Object.entries(values)) {");
        builder.AppendLine("    if (value !== undefined) {");
        builder.AppendLine("      headers.set(name, value);");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine("  return headers;");
        builder.AppendLine("}");
    }

    private static void EmitClientMethod(StringBuilder builder, ApiOperation operation)
    {
        string methodName = ToIdentifier(operation.OperationId, lowerFirst: true);
        string returnType = string.IsNullOrWhiteSpace(operation.ResponseTypeName)
            ? "void"
            : operation.ResponseTypeName;
        string requestParameter = operation.HasRequestType
            ? operation.HasRequiredRequestFields
                ? $"request: {operation.RequestTypeName}, "
                : $"request: {operation.RequestTypeName} = {{}}, "
            : string.Empty;
        string pathExpression = CreatePathExpression(operation.Path, operation.PathParameters);

        builder.AppendLine($"  public {methodName}({requestParameter}init?: ApiRequestInit): Promise<{returnType}> {{");
        builder.AppendLine($"    const path = {pathExpression};");
        builder.Append("    return this.request<").Append(returnType).Append(">(\"")
            .Append(operation.Method.ToUpperInvariant()).Append("\", path, {");

        bool wroteOption = false;
        if (operation.QueryParameters.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("      query: {");
            foreach (var parameter in operation.QueryParameters)
            {
                builder.AppendLine($"        {JsonSerializer.Serialize(parameter.Name)}: {RequestPropertyAccess(parameter.Name)},");
            }

            builder.Append("      }");
            wroteOption = true;
        }

        if (!string.IsNullOrWhiteSpace(operation.BodyTypeName))
        {
            if (wroteOption)
            {
                builder.AppendLine(",");
            }
            else
            {
                builder.AppendLine();
            }

            builder.Append("      body: request.body");
            wroteOption = true;
        }

        if (operation.HeaderParameters.Count > 0)
        {
            if (wroteOption)
            {
                builder.AppendLine(",");
            }
            else
            {
                builder.AppendLine();
            }

            builder.AppendLine("      init: {");
            builder.AppendLine("        ...init,");
            builder.AppendLine("        headers: mergeHeaders(init?.headers, {");
            foreach (var parameter in operation.HeaderParameters)
            {
                string value = RequestPropertyAccess(parameter.Name);
                builder.AppendLine(parameter.Required
                    ? $"          {JsonSerializer.Serialize(parameter.Name)}: String({value}),"
                    : $"          {JsonSerializer.Serialize(parameter.Name)}: {value} === undefined ? undefined : String({value}),");
            }

            builder.AppendLine("        }),");
            builder.Append("      }");
            wroteOption = true;
        }

        if (wroteOption)
        {
            builder.AppendLine(",");
            if (operation.HeaderParameters.Count == 0)
            {
                builder.AppendLine("      init,");
            }
            builder.AppendLine("    });");
        }
        else
        {
            builder.AppendLine(" init });");
        }

        builder.AppendLine("  }");
        builder.AppendLine();
    }

    private static string CreatePathExpression(string path, IReadOnlyList<ApiParameter> pathParameters)
    {
        if (pathParameters.Count == 0)
        {
            return JsonSerializer.Serialize(path);
        }

        string expression = JsonSerializer.Serialize(path);
        foreach (var parameter in pathParameters)
        {
            string token = "{" + parameter.Name + "}";
            string replacement = "${encodePath(" + RequestPropertyAccess(parameter.Name) + ")}";
            expression = expression.Replace(token, replacement, StringComparison.Ordinal);
        }

        return $"`{JsonSerializer.Deserialize<string>(expression)}`";
    }

    private static string CreateOperationId(string method, string path)
    {
        string suffix = string.Concat(path
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => ToIdentifier(part.Trim('{', '}'), lowerFirst: false)));
        return ToIdentifier(method, lowerFirst: true) + suffix;
    }

    private static JsonObject? GetObject(JsonObject root, params string[] path)
    {
        JsonNode? current = root;
        foreach (string segment in path)
        {
            current = current?[segment];
        }

        return current as JsonObject;
    }

    private static string? GetString(JsonObject node, string propertyName)
    {
        return node[propertyName] is JsonValue value && value.TryGetValue<string>(out string? result)
            ? result
            : null;
    }

    private static bool TryGetProperties(JsonObject schema, out JsonObject properties)
    {
        properties = schema["properties"] as JsonObject ?? new JsonObject();
        return properties.Count > 0;
    }

    private static HashSet<string> GetRequiredProperties(JsonObject schema)
    {
        if (schema["required"] is not JsonArray array)
        {
            return new HashSet<string>(StringComparer.Ordinal);
        }

        return array
            .Select(item => item?.GetValue<string>())
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Select(item => item!)
            .ToHashSet(StringComparer.Ordinal);
    }

    private static HashSet<string> GetSchemaTypeNames(JsonObject? schemas)
    {
        if (schemas == null)
        {
            return new HashSet<string>(StringComparer.Ordinal);
        }

        return schemas
            .Select(item => ToTypeName(item.Key))
            .ToHashSet(StringComparer.Ordinal);
    }

    private static void CollectReferencedTypeNames(JsonNode? node, ISet<string> typeNames)
    {
        if (node is JsonObject jsonObject)
        {
            if (GetString(jsonObject, "$ref") is { Length: > 0 } reference &&
                reference.StartsWith("#/components/schemas/", StringComparison.Ordinal))
            {
                typeNames.Add(ToTypeName(reference[(reference.LastIndexOf('/') + 1)..]));
            }

            foreach (var child in jsonObject)
            {
                CollectReferencedTypeNames(child.Value, typeNames);
            }

            return;
        }

        if (node is JsonArray jsonArray)
        {
            foreach (var child in jsonArray)
            {
                CollectReferencedTypeNames(child, typeNames);
            }
        }
    }

    private static string ToTypeName(string value)
    {
        return ToIdentifier(value, lowerFirst: false);
    }

    private static string ToIdentifier(string value, bool lowerFirst)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return lowerFirst ? "unnamed" : "Unnamed";
        }

        var builder = new StringBuilder();
        bool upperNext = !lowerFirst;
        foreach (char ch in value)
        {
            if (char.IsLetterOrDigit(ch))
            {
                builder.Append(builder.Length == 0 && lowerFirst
                    ? char.ToLowerInvariant(ch)
                    : upperNext ? char.ToUpperInvariant(ch) : ch);
                upperNext = false;
            }
            else
            {
                upperNext = true;
            }
        }

        if (builder.Length == 0)
        {
            return lowerFirst ? "unnamed" : "Unnamed";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, lowerFirst ? "value" : "Value");
        }

        return builder.ToString();
    }

    private static string FormatPropertyName(string propertyName)
    {
        return IsIdentifier(propertyName)
            ? propertyName
            : JsonSerializer.Serialize(propertyName);
    }

    private static string RequestPropertyAccess(string propertyName)
    {
        return IsIdentifier(propertyName)
            ? $"request.{propertyName}"
            : $"request[{JsonSerializer.Serialize(propertyName)}]";
    }

    private static bool IsIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            (!char.IsLetter(value[0]) && value[0] != '_' && value[0] != '$'))
        {
            return false;
        }

        return value.Skip(1).All(ch => char.IsLetterOrDigit(ch) || ch == '_' || ch == '$');
    }

    private sealed record ApiOperation(
        string Method,
        string Path,
        string OperationId,
        IReadOnlyList<ApiParameter> PathParameters,
        IReadOnlyList<ApiParameter> QueryParameters,
        IReadOnlyList<ApiParameter> HeaderParameters,
        string? BodyTypeName,
        bool BodyRequired,
        string ResponseTypeName)
    {
        public bool HasRequestType =>
            PathParameters.Count > 0 ||
            QueryParameters.Count > 0 ||
            HeaderParameters.Count > 0 ||
            !string.IsNullOrWhiteSpace(BodyTypeName);

        public bool HasRequiredRequestFields =>
            PathParameters.Any(item => item.Required) ||
            QueryParameters.Any(item => item.Required) ||
            HeaderParameters.Any(item => item.Required) ||
            (!string.IsNullOrWhiteSpace(BodyTypeName) && BodyRequired);

        public string RequestTypeName => $"{ToTypeName(OperationId)}Request";
    }

    private sealed record ApiParameter(
        string Name,
        string Location,
        string TypeName,
        bool Required);
}
