using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using ExportDocManager.Api.Hosting;

var options = GeneratorOptions.Parse(args);
var document = JsonSerializer.SerializeToNode(OpenApiDocumentFactory.Create(new ApiRuntimeOptions
{
    ListenUrls = options.BaseUrl
})) as JsonObject ?? throw new InvalidOperationException("OpenAPI document could not be serialized.");

string generated = TypeScriptClientGenerator.Generate(document);
string? outputDirectory = Path.GetDirectoryName(options.OutputPath);
if (!string.IsNullOrWhiteSpace(outputDirectory))
{
    Directory.CreateDirectory(outputDirectory);
}

File.WriteAllText(options.OutputPath, generated, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated TypeScript API client: {options.OutputPath}");

internal sealed record GeneratorOptions(string OutputPath, string BaseUrl)
{
    public static GeneratorOptions Parse(string[] args)
    {
        string outputPath = Path.Combine(
            "apps",
            "export-doc-web",
            "src",
            "api",
            "generated",
            "exportDocManagerApi.ts");
        string baseUrl = "http://127.0.0.1:5188";

        for (int index = 0; index < args.Length; index++)
        {
            string arg = args[index];
            if (string.Equals(arg, "--output", StringComparison.OrdinalIgnoreCase) && index + 1 < args.Length)
            {
                outputPath = args[++index];
                continue;
            }

            if (string.Equals(arg, "--base-url", StringComparison.OrdinalIgnoreCase) && index + 1 < args.Length)
            {
                baseUrl = args[++index];
                continue;
            }

            throw new ArgumentException($"Unknown or incomplete argument: {arg}");
        }

        return new GeneratorOptions(Path.GetFullPath(outputPath), baseUrl);
    }
}

internal static class TypeScriptClientGenerator
{
    private static readonly string[] HttpMethods = ["get", "post", "put", "delete", "patch"];

    public static string Generate(JsonObject document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var schemas = GetObject(document, "components", "schemas");
        var operations = DiscoverOperations(document);
        var builder = new StringBuilder();

        EmitHeader(builder);
        var schemaTypeNames = GetSchemaTypeNames(schemas);
        EmitSchemaTypes(builder, schemas);
        EmitMissingReferencedSchemaAliases(builder, document, schemaTypeNames);
        EmitOperationRequestTypes(builder, operations);
        EmitClient(builder, operations);

        return builder.ToString();
    }

    private static void EmitHeader(StringBuilder builder)
    {
        builder.AppendLine("/* eslint-disable */");
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by tools/ExportDocManager.ApiClientGenerator from ExportDocManager.Api OpenAPI metadata.");
        builder.AppendLine("// Do not edit this file by hand. Run scripts/generate-api-client.ps1 instead.");
        builder.AppendLine();
    }

    private static void EmitSchemaTypes(StringBuilder builder, JsonObject? schemas)
    {
        if (schemas == null)
        {
            return;
        }

        foreach (var schema in schemas.OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            string typeName = ToTypeName(schema.Key);
            if (schema.Value is not JsonObject schemaObject)
            {
                builder.AppendLine($"export type {typeName} = unknown;");
                builder.AppendLine();
                continue;
            }

            if (TryGetProperties(schemaObject, out var properties))
            {
                var required = GetRequiredProperties(schemaObject);
                builder.AppendLine($"export interface {typeName} {{");
                foreach (var property in properties.OrderBy(item => item.Key, StringComparer.Ordinal))
                {
                    string optional = required.Contains(property.Key) ? string.Empty : "?";
                    string propertyType = SchemaToType(property.Value as JsonObject);
                    builder.AppendLine($"  {FormatPropertyName(property.Key)}{optional}: {propertyType};");
                }

                builder.AppendLine("}");
                builder.AppendLine();
                continue;
            }

            builder.AppendLine($"export type {typeName} = {SchemaToType(schemaObject)};");
            builder.AppendLine();
        }
    }

    private static void EmitMissingReferencedSchemaAliases(
        StringBuilder builder,
        JsonObject document,
        HashSet<string> schemaTypeNames)
    {
        var referencedTypeNames = new SortedSet<string>(StringComparer.Ordinal);
        CollectReferencedTypeNames(document, referencedTypeNames);

        foreach (string typeName in referencedTypeNames)
        {
            if (schemaTypeNames.Contains(typeName))
            {
                continue;
            }

            builder.AppendLine($"export type {typeName} = Record<string, unknown>;");
            builder.AppendLine();
        }
    }

    private static void EmitOperationRequestTypes(StringBuilder builder, IReadOnlyList<ApiOperation> operations)
    {
        foreach (var operation in operations)
        {
            if (!operation.HasRequestType)
            {
                continue;
            }

            builder.AppendLine($"export interface {operation.RequestTypeName} {{");
            foreach (var parameter in operation.PathParameters.Concat(operation.QueryParameters))
            {
                string optional = parameter.Required ? string.Empty : "?";
                builder.AppendLine($"  {FormatPropertyName(parameter.Name)}{optional}: {parameter.TypeName};");
            }

            if (!string.IsNullOrWhiteSpace(operation.BodyTypeName))
            {
                string optional = operation.BodyRequired ? string.Empty : "?";
                builder.AppendLine($"  body{optional}: {operation.BodyTypeName};");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static void EmitClient(StringBuilder builder, IReadOnlyList<ApiOperation> operations)
    {
        builder.AppendLine("export type AccessTokenProvider = string | (() => string | undefined | Promise<string | undefined>);");
        builder.AppendLine("type QueryValue = string | number | boolean | null | undefined;");
        builder.AppendLine("const desktopAccessTokenHeaderName = \"X-ExportDocManager-Desktop-Token\";");
        builder.AppendLine();
        builder.AppendLine("export interface ApiClientOptions {");
        builder.AppendLine("  baseUrl: string;");
        builder.AppendLine("  accessToken?: AccessTokenProvider;");
        builder.AppendLine("  desktopAccessToken?: AccessTokenProvider;");
        builder.AppendLine("  fetch?: typeof globalThis.fetch;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export class ApiError extends Error {");
        builder.AppendLine("  constructor(");
        builder.AppendLine("    public readonly status: number,");
        builder.AppendLine("    public readonly statusText: string,");
        builder.AppendLine("    public readonly responseText: string,");
        builder.AppendLine("  ) {");
        builder.AppendLine("    super(`API request failed with status ${status} ${statusText}`);");
        builder.AppendLine("    this.name = \"ApiError\";");
        builder.AppendLine("  }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export function createExportDocManagerApiClient(options: ApiClientOptions): ExportDocManagerApiClient {");
        builder.AppendLine("  return new ExportDocManagerApiClient(options);");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export class ExportDocManagerApiClient {");
        builder.AppendLine("  private readonly baseUrl: string;");
        builder.AppendLine("  private readonly accessToken?: AccessTokenProvider;");
        builder.AppendLine("  private readonly desktopAccessToken?: AccessTokenProvider;");
        builder.AppendLine("  private readonly fetchImpl: typeof globalThis.fetch;");
        builder.AppendLine();
        builder.AppendLine("  constructor(options: ApiClientOptions) {");
        builder.AppendLine("    this.baseUrl = `${options.baseUrl.replace(/\\/+$/, \"\")}/`;");
        builder.AppendLine("    this.accessToken = options.accessToken;");
        builder.AppendLine("    this.desktopAccessToken = options.desktopAccessToken;");
        builder.AppendLine("    if (typeof options.fetch === \"function\") {");
        builder.AppendLine("      this.fetchImpl = options.fetch;");
        builder.AppendLine("    } else if (typeof globalThis.fetch === \"function\") {");
        builder.AppendLine("      this.fetchImpl = globalThis.fetch.bind(globalThis);");
        builder.AppendLine("    } else {");
        builder.AppendLine("      throw new Error(\"A fetch implementation is required to use ExportDocManagerApiClient.\");");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine();

        foreach (var operation in operations)
        {
            EmitClientMethod(builder, operation);
        }

        builder.AppendLine("  private async resolveAccessToken(): Promise<string | undefined> {");
        builder.AppendLine("    if (typeof this.accessToken === \"function\") {");
        builder.AppendLine("      return this.accessToken();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    return this.accessToken;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  private async resolveDesktopAccessToken(): Promise<string | undefined> {");
        builder.AppendLine("    if (typeof this.desktopAccessToken === \"function\") {");
        builder.AppendLine("      return this.desktopAccessToken();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    return this.desktopAccessToken;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  private async request<T>(");
        builder.AppendLine("    method: string,");
        builder.AppendLine("    path: string,");
        builder.AppendLine("    options: { query?: Record<string, QueryValue>; body?: unknown; init?: RequestInit } = {},");
        builder.AppendLine("  ): Promise<T> {");
        builder.AppendLine("    const { headers: initHeaders, body: _ignoredBody, ...restInit } = options.init ?? {};");
        builder.AppendLine("    const headers = new Headers(initHeaders);");
        builder.AppendLine("    const isFormDataBody = typeof FormData !== \"undefined\" && options.body instanceof FormData;");
        builder.AppendLine("    const isBlobBody = typeof Blob !== \"undefined\" && options.body instanceof Blob;");
        builder.AppendLine("    if (!headers.has(\"Accept\")) {");
        builder.AppendLine("      headers.set(\"Accept\", \"application/json\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    if (options.body !== undefined && !headers.has(\"Content-Type\")) {");
        builder.AppendLine("      if (isBlobBody) {");
        builder.AppendLine("        headers.set(\"Content-Type\", \"application/octet-stream\");");
        builder.AppendLine("      } else if (!isFormDataBody) {");
        builder.AppendLine("        headers.set(\"Content-Type\", \"application/json\");");
        builder.AppendLine("      }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    const desktopToken = await this.resolveDesktopAccessToken();");
        builder.AppendLine("    if (desktopToken && !headers.has(desktopAccessTokenHeaderName)) {");
        builder.AppendLine("      headers.set(desktopAccessTokenHeaderName, desktopToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    const token = await this.resolveAccessToken();");
        builder.AppendLine("    if (token && !headers.has(\"Authorization\")) {");
        builder.AppendLine("      headers.set(\"Authorization\", `Bearer ${token}`);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    const relativePath = appendQuery(path, options.query).replace(/^\\/+/, \"\");");
        builder.AppendLine("    const url = new URL(relativePath, this.baseUrl);");
        builder.AppendLine("    const requestInit: RequestInit = { ...restInit, method, headers };");
        builder.AppendLine("    if (options.body !== undefined) {");
        builder.AppendLine("      requestInit.body = isFormDataBody || isBlobBody ? options.body as BodyInit : JSON.stringify(options.body);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    const response = await this.fetchImpl(url, requestInit);");
        builder.AppendLine("    const contentType = response.headers.get(\"content-type\") ?? \"\";");
        builder.AppendLine("    const contentDisposition = response.headers.get(\"content-disposition\") ?? \"\";");
        builder.AppendLine("    if (contentType.includes(\"application/octet-stream\") || contentDisposition.toLowerCase().includes(\"attachment\")) {");
        builder.AppendLine("      if (!response.ok) {");
        builder.AppendLine("        throw new ApiError(response.status, response.statusText, await response.text());");
        builder.AppendLine("      }");
        builder.AppendLine();
        builder.AppendLine("      return await response.blob() as T;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    const responseText = await response.text();");
        builder.AppendLine("    if (!response.ok) {");
        builder.AppendLine("      throw new ApiError(response.status, response.statusText, responseText);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    if (!responseText) {");
        builder.AppendLine("      return undefined as T;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    return (contentType.includes(\"application/json\") ? JSON.parse(responseText) : responseText) as T;");
        builder.AppendLine("  }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function appendQuery(path: string, query?: Record<string, QueryValue>): string {");
        builder.AppendLine("  const entries = Object.entries(query ?? {}).filter(([, value]) => value !== undefined && value !== null && value !== \"\");");
        builder.AppendLine("  if (entries.length === 0) {");
        builder.AppendLine("    return path;");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  const search = new URLSearchParams();");
        builder.AppendLine("  for (const [key, value] of entries) {");
        builder.AppendLine("    search.append(key, String(value));");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  return `${path}?${search.toString()}`;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function encodePath(value: string | number | boolean): string {");
        builder.AppendLine("  return encodeURIComponent(String(value));");
        builder.AppendLine("}");
    }

    private static void EmitClientMethod(StringBuilder builder, ApiOperation operation)
    {
        string methodName = ToIdentifier(operation.OperationId, lowerFirst: true);
        string returnType = string.IsNullOrWhiteSpace(operation.ResponseTypeName)
            ? "void"
            : operation.ResponseTypeName;
        string requestParameter = operation.HasRequestType
            ? operation.HasRequiredRequestFields
                ? $"request: {operation.RequestTypeName}, "
                : $"request: {operation.RequestTypeName} = {{}}, "
            : string.Empty;
        string pathExpression = CreatePathExpression(operation.Path, operation.PathParameters);

        builder.AppendLine($"  public {methodName}({requestParameter}init?: RequestInit): Promise<{returnType}> {{");
        builder.AppendLine($"    const path = {pathExpression};");
        builder.Append("    return this.request<").Append(returnType).Append(">(\"")
            .Append(operation.Method.ToUpperInvariant()).Append("\", path, {");

        bool wroteOption = false;
        if (operation.QueryParameters.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("      query: {");
            foreach (var parameter in operation.QueryParameters)
            {
                builder.AppendLine($"        {JsonSerializer.Serialize(parameter.Name)}: {RequestPropertyAccess(parameter.Name)},");
            }

            builder.Append("      }");
            wroteOption = true;
        }

        if (!string.IsNullOrWhiteSpace(operation.BodyTypeName))
        {
            if (wroteOption)
            {
                builder.AppendLine(",");
            }
            else
            {
                builder.AppendLine();
            }

            builder.Append("      body: request.body");
            wroteOption = true;
        }

        if (wroteOption)
        {
            builder.AppendLine(",");
            builder.AppendLine("      init,");
            builder.AppendLine("    });");
        }
        else
        {
            builder.AppendLine(" init });");
        }

        builder.AppendLine("  }");
        builder.AppendLine();
    }

    private static IReadOnlyList<ApiOperation> DiscoverOperations(JsonObject document)
    {
        var operations = new List<ApiOperation>();
        var paths = GetObject(document, "paths") ?? throw new InvalidOperationException("OpenAPI document does not contain paths.");

        foreach (var path in paths.OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            if (path.Value is not JsonObject pathObject)
            {
                continue;
            }

            foreach (string method in HttpMethods)
            {
                if (pathObject[method] is not JsonObject operationObject)
                {
                    continue;
                }

                string operationId = GetString(operationObject, "operationId") ??
                    CreateOperationId(method, path.Key);
                var parameters = ReadParameters(operationObject);
                var requestBody = operationObject["requestBody"] as JsonObject;
                string? bodyType = ContentToType(requestBody?["content"]);
                bool bodyRequired = requestBody?["required"]?.GetValue<bool>() ?? false;
                string responseType = ReadResponseType(operationObject);

                operations.Add(new ApiOperation(
                    method,
                    path.Key,
                    operationId,
                    parameters.Where(item => item.Location == "path").ToArray(),
                    parameters.Where(item => item.Location == "query").ToArray(),
                    bodyType,
                    bodyRequired,
                    responseType));
            }
        }

        return operations
            .OrderBy(item => item.OperationId, StringComparer.Ordinal)
            .ToArray();
    }

    private static IReadOnlyList<ApiParameter> ReadParameters(JsonObject operation)
    {
        var parameters = new List<ApiParameter>();
        if (operation["parameters"] is not JsonArray array)
        {
            return parameters;
        }

        foreach (var item in array)
        {
            if (item is not JsonObject parameter)
            {
                continue;
            }

            string? parameterName = GetString(parameter, "name");
            if (string.IsNullOrWhiteSpace(parameterName))
            {
                continue;
            }

            string location = GetString(parameter, "in") ?? string.Empty;
            bool required = string.Equals(location, "path", StringComparison.OrdinalIgnoreCase) ||
                (parameter["required"]?.GetValue<bool>() ?? false);
            string typeName = SchemaToType(parameter["schema"] as JsonObject);
            parameters.Add(new ApiParameter(parameterName, location, typeName, required));
        }

        return parameters;
    }

    private static string ReadResponseType(JsonObject operation)
    {
        if (operation["responses"] is not JsonObject responses)
        {
            return "void";
        }

        foreach (string preferred in new[] { "200", "201", "202", "204" })
        {
            if (responses[preferred] is JsonObject response)
            {
                return ContentToType(response["content"]) ?? "void";
            }
        }

        foreach (var response in responses)
        {
            if (response.Key.Length == 3 &&
                response.Key[0] == '2' &&
                response.Value is JsonObject responseObject)
            {
                return ContentToType(responseObject["content"]) ?? "void";
            }
        }

        return "void";
    }

    private static string? ContentToType(JsonNode? content)
    {
        if (content is not JsonObject contentObject)
        {
            return null;
        }

        if (contentObject["application/octet-stream"] is JsonObject)
        {
            return "Blob";
        }

        foreach (var entry in contentObject)
        {
            if (entry.Value is JsonObject mediaType &&
                mediaType["schema"] is JsonObject binarySchema &&
                string.Equals(binarySchema["format"]?.GetValue<string>(), "binary", StringComparison.OrdinalIgnoreCase))
            {
                return "Blob";
            }
        }

        if (contentObject["multipart/form-data"] is JsonObject)
        {
            return "FormData";
        }

        if (contentObject["application/json"] is not JsonObject jsonContent ||
            jsonContent["schema"] is not JsonObject schema)
        {
            return null;
        }

        return SchemaToType(schema);
    }

    private static string SchemaToType(JsonObject? schema)
    {
        if (schema == null)
        {
            return "unknown";
        }

        if (GetString(schema, "$ref") is { Length: > 0 } reference)
        {
            return ToTypeName(reference[(reference.LastIndexOf('/') + 1)..]);
        }

        string? type = GetString(schema, "type");
        return type switch
        {
            "array" => $"{SchemaToType(schema["items"] as JsonObject)}[]",
            "boolean" => "boolean",
            "integer" => "number",
            "number" => "number",
            "string" => "string",
            "object" when TryGetProperties(schema, out var properties) => InlineObjectType(properties, GetRequiredProperties(schema)),
            "object" => "Record<string, unknown>",
            _ when TryGetProperties(schema, out var properties) => InlineObjectType(properties, GetRequiredProperties(schema)),
            _ => "unknown"
        };
    }

    private static string InlineObjectType(JsonObject properties, HashSet<string> required)
    {
        var parts = properties
            .OrderBy(item => item.Key, StringComparer.Ordinal)
            .Select(item =>
            {
                string optional = required.Contains(item.Key) ? string.Empty : "?";
                return $"{FormatPropertyName(item.Key)}{optional}: {SchemaToType(item.Value as JsonObject)}";
            });

        return $"{{ {string.Join("; ", parts)} }}";
    }

    private static string CreatePathExpression(string path, IReadOnlyList<ApiParameter> pathParameters)
    {
        if (pathParameters.Count == 0)
        {
            return JsonSerializer.Serialize(path);
        }

        string expression = JsonSerializer.Serialize(path);
        foreach (var parameter in pathParameters)
        {
            string token = "{" + parameter.Name + "}";
            string replacement = "${encodePath(" + RequestPropertyAccess(parameter.Name) + ")}";
            expression = expression.Replace(token, replacement, StringComparison.Ordinal);
        }

        return $"`{JsonSerializer.Deserialize<string>(expression)}`";
    }

    private static string CreateOperationId(string method, string path)
    {
        string suffix = string.Concat(path
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => ToIdentifier(part.Trim('{', '}'), lowerFirst: false)));
        return ToIdentifier(method, lowerFirst: true) + suffix;
    }

    private static JsonObject? GetObject(JsonObject root, params string[] path)
    {
        JsonNode? current = root;
        foreach (string segment in path)
        {
            current = current?[segment];
        }

        return current as JsonObject;
    }

    private static string? GetString(JsonObject node, string propertyName)
    {
        return node[propertyName]?.GetValue<string>();
    }

    private static bool TryGetProperties(JsonObject schema, out JsonObject properties)
    {
        properties = schema["properties"] as JsonObject ?? new JsonObject();
        return properties.Count > 0;
    }

    private static HashSet<string> GetRequiredProperties(JsonObject schema)
    {
        if (schema["required"] is not JsonArray array)
        {
            return new HashSet<string>(StringComparer.Ordinal);
        }

        return array
            .Select(item => item?.GetValue<string>())
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Select(item => item!)
            .ToHashSet(StringComparer.Ordinal);
    }

    private static HashSet<string> GetSchemaTypeNames(JsonObject? schemas)
    {
        if (schemas == null)
        {
            return new HashSet<string>(StringComparer.Ordinal);
        }

        return schemas
            .Select(item => ToTypeName(item.Key))
            .ToHashSet(StringComparer.Ordinal);
    }

    private static void CollectReferencedTypeNames(JsonNode? node, ISet<string> typeNames)
    {
        if (node is JsonObject jsonObject)
        {
            if (GetString(jsonObject, "$ref") is { Length: > 0 } reference &&
                reference.StartsWith("#/components/schemas/", StringComparison.Ordinal))
            {
                typeNames.Add(ToTypeName(reference[(reference.LastIndexOf('/') + 1)..]));
            }

            foreach (var child in jsonObject)
            {
                CollectReferencedTypeNames(child.Value, typeNames);
            }

            return;
        }

        if (node is JsonArray jsonArray)
        {
            foreach (var child in jsonArray)
            {
                CollectReferencedTypeNames(child, typeNames);
            }
        }
    }

    private static string ToTypeName(string value)
    {
        return ToIdentifier(value, lowerFirst: false);
    }

    private static string ToIdentifier(string value, bool lowerFirst)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return lowerFirst ? "unnamed" : "Unnamed";
        }

        var builder = new StringBuilder();
        bool upperNext = !lowerFirst;
        foreach (char ch in value)
        {
            if (char.IsLetterOrDigit(ch))
            {
                builder.Append(builder.Length == 0 && lowerFirst
                    ? char.ToLowerInvariant(ch)
                    : upperNext ? char.ToUpperInvariant(ch) : ch);
                upperNext = false;
            }
            else
            {
                upperNext = true;
            }
        }

        if (builder.Length == 0)
        {
            return lowerFirst ? "unnamed" : "Unnamed";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, lowerFirst ? "value" : "Value");
        }

        return builder.ToString();
    }

    private static string FormatPropertyName(string propertyName)
    {
        return IsIdentifier(propertyName)
            ? propertyName
            : JsonSerializer.Serialize(propertyName);
    }

    private static string RequestPropertyAccess(string propertyName)
    {
        return IsIdentifier(propertyName)
            ? $"request.{propertyName}"
            : $"request[{JsonSerializer.Serialize(propertyName)}]";
    }

    private static bool IsIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            (!char.IsLetter(value[0]) && value[0] != '_' && value[0] != '$'))
        {
            return false;
        }

        return value.Skip(1).All(ch => char.IsLetterOrDigit(ch) || ch == '_' || ch == '$');
    }

    private sealed record ApiOperation(
        string Method,
        string Path,
        string OperationId,
        IReadOnlyList<ApiParameter> PathParameters,
        IReadOnlyList<ApiParameter> QueryParameters,
        string? BodyTypeName,
        bool BodyRequired,
        string ResponseTypeName)
    {
        public bool HasRequestType =>
            PathParameters.Count > 0 ||
            QueryParameters.Count > 0 ||
            !string.IsNullOrWhiteSpace(BodyTypeName);

        public bool HasRequiredRequestFields =>
            PathParameters.Any(item => item.Required) ||
            QueryParameters.Any(item => item.Required) ||
            (!string.IsNullOrWhiteSpace(BodyTypeName) && BodyRequired);

        public string RequestTypeName => $"{ToTypeName(OperationId)}Request";
    }

    private sealed record ApiParameter(
        string Name,
        string Location,
        string TypeName,
        bool Required);
}
