export const permissionResources = {
  salesDashboard: "sales.dashboard",
  crmCustomers: "sales.customers",
  crmContacts: "sales.contacts",
  crmFollowUps: "sales.follow-ups",
  salesOpportunities: "sales.opportunities",
  salesQuotes: "sales.quotes",
  suppliers: "sales.suppliers",
  supplierContacts: "sales.supplier-contacts",
  supplierProductLinks: "sales.supplier-product-links",
  supplierAssessments: "sales.supplier-assessments",
  emailTemplates: "sales.email-templates",
  emailDelivery: "common.email-delivery",
  reportTemplates: "document.report-templates",
  reportResources: "document.report-resources",
  invoiceOutput: "document.invoice-output",
  paymentOutput: "document.payment-output",
} as const;

export const permissionActions = {
  view: "view",
  create: "create",
  edit: "edit",
  deactivate: "deactivate",
  delete: "delete",
  import: "import",
  export: "export",
  assign: "assign",
  setPrimary: "set-primary",
  complete: "complete",
  restore: "restore",
  transition: "transition",
  approve: "approve",
  archive: "archive",
  admit: "admit",
  publish: "publish",
  share: "share",
  clone: "clone",
  design: "design",
  upload: "upload",
  recycle: "recycle",
  preview: "preview",
  print: "print",
  exportPdf: "export-pdf",
  exportZip: "export-zip",
  sendEmail: "send-email",
  send: "send",
  viewDelivery: "view-delivery",
} as const;

export function resolveReportTemplateAccess(hasAccess: (action: string) => boolean) {
  return {
    view: hasAccess(permissionActions.view),
    design: hasAccess(permissionActions.design),
    clone: hasAccess(permissionActions.clone),
    publish: hasAccess(permissionActions.publish),
    share: hasAccess(permissionActions.share),
    deactivate: hasAccess(permissionActions.deactivate),
    archive: hasAccess(permissionActions.archive),
    restore: hasAccess(permissionActions.restore),
    import: hasAccess(permissionActions.import),
    export: hasAccess(permissionActions.export),
  } as const;
}
export type ReportTemplatePermissionAccess = ReturnType<typeof resolveReportTemplateAccess>;
