use crate::form_sections::Section;
use export_doc_domain::single_window::Business;

pub fn document(business: Business) -> Vec<Section> {
    if business == Business::Acd {
        return vec![
            Section::new(
                "acd.identity",
                "企业与操作资料",
                &["copCusCode", "operType", "sign"],
                true,
            ),
            Section::new(
                "acd.declaration",
                "核心申报信息",
                &[
                    "gName",
                    "codeTS",
                    "declTotal",
                    "curr",
                    "ieDate",
                    "tradeMode",
                    "oriCountry",
                    "tradeCode",
                    "agentCode",
                ],
                true,
            ),
            Section::new(
                "acd.goods",
                "货物与联系",
                &[
                    "qtyOrWeight",
                    "packingCondition",
                    "consignTele",
                    "otherNote",
                    "listNo",
                ],
                true,
            ),
            Section::new(
                "acd.documents",
                "单证与费用",
                &[
                    "paperInfo",
                    "receiveDate",
                    "otherRecInfo",
                    "declarePrice",
                    "promiseNote",
                    "declTele",
                ],
                false,
            ),
            Section::new(
                "acd.receipt",
                "回执回写信息",
                &["entryId", "consignNo", "counterpartyStatus"],
                false,
            ),
        ];
    }
    vec![
        Section::new(
            "coo.identity",
            "证书基础",
            &[
                "applyType",
                "certStatus",
                "certType",
                "certNo",
                "entMgrNo",
                "ciqRegNo",
                "aplRegNo",
                "etpsName",
            ],
            true,
        ),
        Section::new(
            "coo.application",
            "申报与对象",
            &[
                "applName",
                "applicant",
                "applTel",
                "orgCode",
                "fetchPlace",
                "aplAdd",
                "aplDate",
                "invNo",
                "invDate",
                "destCountryCode",
                "destCountryName",
                "destCountry",
                "exporter",
                "consignee",
            ],
            true,
        ),
        Section::new(
            "coo.contacts",
            "出口商及收货人联系方式",
            &[
                "exporterTel",
                "exporterFax",
                "exporterEmail",
                "consigneeTel",
                "consigneeFax",
                "consigneeEmail",
            ],
            false,
        ),
        Section::new(
            "coo.trade",
            "运输与贸易",
            &[
                "loadPort",
                "unloadPort",
                "transMeans",
                "transName",
                "transCountryCode",
                "transCountryName",
                "transPort",
                "destPort",
                "transDetails",
                "intendExpDate",
                "tradeModeCode",
                "fobValue",
                "totalAmt",
                "curr",
                "priceTerms",
                "goodsSpecClause",
                "mark",
                "note",
            ],
            true,
        ),
        Section::new(
            "coo.extra",
            "补充与特殊项",
            &[
                "lcNo",
                "specInvTerms",
                "remark",
                "producer",
                "producerSertFlag",
                "exhibitFlag",
                "thirdPartyInvFlag",
                "predictFlag",
                "expDeclDate",
                "oriCountryCode",
                "oriCountry",
                "chkValidDate",
                "etpsConcEr",
                "etpsTel",
                "entryId",
                "prcsAssembly",
                "aplPromiseCode",
            ],
            false,
        ),
        Section::new(
            "coo.reissue",
            "更改与重发",
            &[
                "oldCertNo",
                "modReason",
                "modColm",
                "oldSituDesc",
                "modSituDesc",
                "oldDeclDate",
                "oldIssueDate",
            ],
            false,
        ),
    ]
}

pub fn goods() -> Vec<Section> {
    vec![
        Section::new(
            "goods.basic",
            "货物基础",
            &[
                "goodsItemFlag",
                "hsCode",
                "goodsName",
                "goodsNameE",
                "goodsDesc",
                "invNo",
            ],
            true,
        ),
        Section::new(
            "goods.quantity",
            "数量、包装与金额",
            &[
                "packQty",
                "packUnit",
                "packType",
                "goodsQty",
                "goodsQtyRef",
                "goodsUnitE",
                "goodsUnit",
                "goodsUnitRef",
                "secdGoodsQtyRef",
                "secdGoodsUnitRef",
                "grossWt",
                "netWt",
                "wtUnit",
                "invPrice",
                "invValue",
                "fobValue",
                "goodsTaxRate",
            ],
            true,
        ),
        Section::new(
            "goods.origin",
            "原产地标准",
            &[
                "oriCriteria",
                "oriCriteriaRef",
                "oriCriteriaSub",
                "goodsOriginCountry",
                "goodsOriginCountryEn",
                "iCompPrpr",
            ],
            true,
        ),
        Section::new(
            "goods.producer",
            "生产企业",
            &[
                "ciqRegNo",
                "prdcEtpsName",
                "prdcEtpsConcEr",
                "prdcEtpsTel",
                "producer",
                "producerTel",
                "producerFax",
                "producerEmail",
                "producerSertFlag",
            ],
            false,
        ),
    ]
}

pub fn label(scope: &str, key: &str) -> String {
    let translated = export_doc_domain::single_window::label(scope, key);
    if translated != key {
        return translated;
    }
    match key {
        "profileName" => "档案名称",
        "companyScope" => "公司抬头",
        "cardIdentifier" => "操作卡标识",
        "customsCooClientRootPath" => "原产地证交接目录（相对路径）",
        "agentConsignmentClientRootPath" => "代理委托交接目录（相对路径）",
        "canSubmitCustomsCoo" => "启用原产地证",
        "canSubmitAgentConsignment" => "启用代理委托",
        "code" => "代码",
        "chineseName" => "中文名称",
        "englishName" => "英文名称",
        "alphaCode" => "字母代码",
        "acdCode" => "代理委托代码",
        "name" => "名称",
        "value" => "标准值",
        "description" => "说明",
        "aliases" => "别名（每行一个）",
        "fileName" => "附件文件名",
        "fileType" => "附件类型",
        "docType" => "单据类型",
        "isDelay" => "延期提交",
        "entName" => "企业名称",
        "entAddr" => "企业地址",
        "entCountryCode" => "所在国家代码",
        "entCountryName" => "所在国家名称",
        "producer" => "生产企业英文名称与地址",
        "prdcEtpsName" => "生产企业名称",
        "ciqRegNo" => "生产企业代码",
        "producerTel" => "生产企业电话",
        "producerFax" => "生产企业传真",
        "producerEmail" => "生产企业邮箱",
        "entryId" => "报关单号",
        "consignNo" => "委托编号",
        "counterpartyStatus" => "对方状态",
        _ => key,
    }
    .into()
}
