export global Query {
    in-out property <string> start;
    in-out property <string> end;
    in-out property <string> keyword;
    in-out property <string> contract;
    in-out property <string> style-name;
    in-out property <string> style-no;
    in-out property <[string]> customers;
    in-out property <[string]> exporters;
    in-out property <int> customer-index:0;
    in-out property <int> exporter-index:0;
    in-out property <int> type-index:0;
    in-out property <int> transport-index:0;
    in-out property <int> page-size-index:1;
    in-out property <bool> advanced:false;
    in-out property <bool> can-export:false;
    in-out property <bool> can-open:false;
    callback action(string);
}
export global InvoiceFiles {
    in-out property <bool> open:false;
    in-out property <bool> valid:false;
    in-out property <bool> can-import:false;
    in-out property <bool> can-export:false;
    in-out property <bool> conflict:false;
    in-out property <string> name;
    in-out property <string> summary;
    in-out property <string> new-number;
    in-out property <int> action-index:0;
    callback action(string);
}
