export struct DocumentPackageRow {
    name: string,
    template-path: string,
    selected: bool,
    with-seal: bool,
}

export global DocumentPackage {
    in-out property <[DocumentPackageRow]> rows;
    in-out property <int> selected-count:0;
    in-out property <bool> include-merged-pdf:true;
    in-out property <bool> can-preview:false;
    in-out property <bool> can-export:false;
    callback action(string);
    callback template-toggled(string, bool);
}
