CREATE TABLE schema_version (version BIGINT PRIMARY KEY CHECK(version = 4));
INSERT INTO schema_version VALUES (4);
CREATE TABLE records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    identity TEXT,
    version BIGINT NOT NULL CHECK(version > 0),
    owner_id BIGINT NOT NULL,
    company TEXT NOT NULL,
    department TEXT NOT NULL,
    search_text TEXT NOT NULL DEFAULT '',
    body JSONB NOT NULL,
    UNIQUE(kind, identity)
);
CREATE INDEX records_kind_id ON records(kind, id DESC);
CREATE INDEX records_scope ON records(kind, company, department, owner_id);
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    record_id BIGINT NOT NULL,
    version BIGINT NOT NULL,
    action TEXT NOT NULL,
    actor_id BIGINT NOT NULL,
    occurred_at TEXT NOT NULL,
    note TEXT NOT NULL,
    body JSONB NOT NULL
);
CREATE INDEX history_record ON history(kind, record_id, id DESC);
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    record_id BIGINT NOT NULL,
    version BIGINT NOT NULL,
    action TEXT NOT NULL,
    actor_id BIGINT NOT NULL,
    occurred_at TEXT NOT NULL,
    body JSONB NOT NULL
);
CREATE INDEX audit_logs_time ON audit_logs(occurred_at, id DESC);
CREATE TABLE credentials (
    user_id BIGINT PRIMARY KEY REFERENCES records(id) ON DELETE CASCADE,
    salt BYTEA NOT NULL,
    password_hash BYTEA NOT NULL,
    iterations BIGINT NOT NULL CHECK(iterations >= 600000)
);
CREATE TABLE settings (
    name TEXT PRIMARY KEY,
    version BIGINT NOT NULL,
    body JSONB NOT NULL
);
CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    record_id BIGINT NOT NULL REFERENCES records(id) ON DELETE RESTRICT,
    file_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    digest TEXT NOT NULL,
    content BYTEA NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX files_record ON files(kind, record_id);
