#!/bin/sh
set -eu

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${EXPORTDOCMANAGER_POSTGRES_APP_USER:?EXPORTDOCMANAGER_POSTGRES_APP_USER is required}"
: "${EXPORTDOCMANAGER_POSTGRES_APP_PASSWORD:?EXPORTDOCMANAGER_POSTGRES_APP_PASSWORD is required}"
: "${EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE:?EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE is required}"
: "${EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER:?EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER is required}"
: "${EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_PASSWORD:?EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_PASSWORD is required}"

validate_role_name() {
  case "$2" in
    ''|*[!A-Za-z0-9_]*)
      echo "$1 must contain only ASCII letters, digits, or underscores." >&2
      exit 1
      ;;
  esac
  [ "${#2}" -le 63 ] || {
    echo "$1 must not exceed 63 characters." >&2
    exit 1
  }
}

validate_role_name POSTGRES_USER "$POSTGRES_USER"
validate_role_name EXPORTDOCMANAGER_POSTGRES_APP_USER "$EXPORTDOCMANAGER_POSTGRES_APP_USER"
validate_role_name EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE "$EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE"
validate_role_name EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER"

[ "$POSTGRES_USER" != "$EXPORTDOCMANAGER_POSTGRES_APP_USER" ] &&
  [ "$POSTGRES_USER" != "$EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE" ] &&
  [ "$POSTGRES_USER" != "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER" ] &&
  [ "$EXPORTDOCMANAGER_POSTGRES_APP_USER" != "$EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE" ] &&
  [ "$EXPORTDOCMANAGER_POSTGRES_APP_USER" != "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER" ] &&
  [ "$EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE" != "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER" ] || {
    echo "PostgreSQL administrator, owner, application, and maintenance roles must be distinct." >&2
    exit 1
  }

[ "$POSTGRES_PASSWORD" != "$EXPORTDOCMANAGER_POSTGRES_APP_PASSWORD" ] &&
  [ "$POSTGRES_PASSWORD" != "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_PASSWORD" ] &&
  [ "$EXPORTDOCMANAGER_POSTGRES_APP_PASSWORD" != "$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_PASSWORD" ] || {
    echo "PostgreSQL administrator, application, and maintenance passwords must be distinct." >&2
    exit 1
  }

psql --quiet --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=database_name="$POSTGRES_DB" \
  --set=administrator_role="$POSTGRES_USER" \
  --set=owner_role="$EXPORTDOCMANAGER_POSTGRES_OWNER_ROLE" \
  --set=app_role="$EXPORTDOCMANAGER_POSTGRES_APP_USER" \
  --set=app_password="$EXPORTDOCMANAGER_POSTGRES_APP_PASSWORD" \
  --set=maintenance_role="$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_USER" \
  --set=maintenance_password="$EXPORTDOCMANAGER_POSTGRES_MAINTENANCE_PASSWORD" <<'SQL'
SELECT format('CREATE ROLE %I NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION', :'owner_role')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'owner_role')
\gexec

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION', :'app_role', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_role')
\gexec

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER CREATEDB NOCREATEROLE NOREPLICATION', :'maintenance_role', :'maintenance_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'maintenance_role')
\gexec

ALTER ROLE :"owner_role" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE :"app_role" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE :"maintenance_role" LOGIN NOSUPERUSER CREATEDB NOCREATEROLE NOREPLICATION;
GRANT :"owner_role" TO :"maintenance_role";

ALTER DATABASE :"database_name" OWNER TO :"owner_role";
REVOKE ALL ON DATABASE :"database_name" FROM PUBLIC;
GRANT CONNECT ON DATABASE :"database_name" TO :"administrator_role";
GRANT CONNECT, TEMPORARY ON DATABASE :"database_name" TO :"app_role";
GRANT CONNECT, TEMPORARY ON DATABASE :"database_name" TO :"maintenance_role";
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO :"app_role";

ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"app_role";
ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"app_role";
ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public
  GRANT EXECUTE ON ROUTINES TO :"app_role";
SQL
