<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ExportDocManager.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExportDocManager.Domain\ExportDocManager.Domain.csproj" />
    <Compile Include="..\..\Shared\Security\LicenseKeyCodec.cs" Link="Shared\Security\LicenseKeyCodec.cs" />
  </ItemGroup>

</Project>
