import assert from 'node:assert/strict';
import path from 'node:path';
import { withOfficeUi } from './lib/native-office-ui.mjs';

await withOfficeUi('template-private-ui', async ({ output, url, invoke, openPage }) => {
  const login = await invoke('Login', { username: 'oa-review', password: 'Review-2026-Test' });
  const admin = login.accessToken;
  const grants = ['view', 'design', 'clone'].map(action => ({ resourceKey: 'document.report-templates', action, dataScope: 'company' }));
  grants.push({ resourceKey: 'document.invoices', action: 'view', dataScope: 'company' });
  const role = await invoke('CreatePermissionTemplate', { code: 'PRIVATE-DESIGN', name: '私人模板设计', isActive: true, grants }, {}, admin);
  for (const username of ['private-owner', 'private-other']) {
    await invoke('createUserAccount', { username, fullName: username, role: 'User', companyScope: 'DEFAULT', departmentId: 'GENERAL', permissionTemplateId: role.id, isActive: true, resetPassword: 'Private-Test-2026' }, {}, admin);
  }
  const file = await invoke('CreateReportTemplate', { reportType: 'ExportDocument', displayName: '团队公共原稿', templatePath: 'user:Export/team-template.dtpl' }, {}, admin);
  await invoke('SetDefaultReportTemplate', { reportType: 'ExportDocument', templatePath: file.templatePath }, {}, admin);
  const ownerSession = await invoke('Login', { username: 'private-owner', password: 'Private-Test-2026' });
  assert(ownerSession.user.capabilities.permissions.some(grant => grant.resourceKey === 'document.report-templates' && grant.action === 'view'), JSON.stringify(ownerSession.user.capabilities));
  const page = await openPage('private-owner', 'Private-Test-2026');
  await page.waitForURL('**/#/invoices');
  await page.goto(`${url}/#/reports/templates/manage`);
  await page.locator('.template-select-field select').selectOption(file.templatePath);
  assert(await page.getByRole('button', { name: '当前全局默认', exact: true }).isDisabled());
  assert.equal(await page.getByLabel('新建模板', { exact: true }).count(), 0);
  await page.locator('details[aria-label="我的和共享模板"] > summary').click();
  await page.getByLabel('新模板名称', { exact: true }).fill('私人发票样式');
  const cloned = page.waitForResponse(response => response.url().endsWith('/api/reports/user-templates/clone') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '复制当前模板', exact: true }).click();
  const copy = await (await cloned).json();
  assert.equal(copy.status, 'Draft'); assert.equal(copy.shareScope, 'Private');
  await page.getByRole('heading', { name: '私人发票样式', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '发布（为共享准备）', exact: true }).count(), 0);
  await page.getByRole('button', { name: '打开设计器', exact: true }).click();
  const design = JSON.parse(copy.contentHtml);
  const first = design.layers.flatMap(layer => layer.elements).find(element => element.type === 'Text');
  assert(first, 'Starter includes editable text');
  const element = page.locator(`[data-v3-element-id="${first.id}"]`);
  await element.waitFor(); await element.click(); await element.press('ArrowRight');
  await page.locator('.report-designer-v3-sidebar-tabs button').filter({ hasText: '图层' }).click();
  const layerRow = role => page.getByLabel(`${design.layers.find(layer => layer.role === role).name}图层`, { exact: true });
  const header = layerRow('Header'), footer = layerRow('Footer');
  await header.getByText('图层设置', { exact: true }).click();
  await header.getByText('打印行为', { exact: true }).click();
  await header.getByLabel('仅首页输出', { exact: true }).check();
  await footer.getByText('图层设置', { exact: true }).click();
  await footer.getByText('打印行为', { exact: true }).click();
  await footer.getByLabel('页脚贴底', { exact: true }).uncheck();
  await footer.getByLabel('跟随正文（签字区、条款）', { exact: true }).check();
  const savedResponse = page.waitForResponse(response => response.url().includes(`/api/reports/user-templates/${copy.id}`) && response.request().method() === 'PUT');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const saved = await (await savedResponse).json();
  assert.equal(saved.status, 'Draft'); assert.equal(saved.shareScope, 'Private');
  assert.notEqual(saved.contentHtml, copy.contentHtml, 'Canvas edit saved');
  const savedDesign = JSON.parse(saved.contentHtml);
  assert.equal(savedDesign.layers.find(layer => layer.role === 'Header').print.firstPageOnly, true);
  assert.equal(savedDesign.layers.find(layer => layer.role === 'Footer').print.followBody, true);
  assert.equal(savedDesign.layers.find(layer => layer.role === 'Footer').print.pinToPageBottom, false);
  await page.getByText('私人模板已保存，可直接用于自己的打印和导出，无需发布。', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(output, 'private-design-saved.png'), fullPage: true });
  await page.getByRole('tab', { name: '预览', exact: true }).click();
  await page.getByRole('button', { name: '样例预览', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('iframe[title="模板预览"]')?.srcdoc.includes('<svg'));
  await page.screenshot({ path: path.join(output, 'private-native-preview.png'), fullPage: true });
  const catalog = await invoke('ListReportTemplates', undefined, {}, ownerSession.accessToken);
  const packing = catalog.find(template => template.templatePath.endsWith('packing_list_template.dtpl'));
  assert(packing, 'Built-in packing template is available for detail editing');
  const detailCopy = await invoke('CloneUserReportTemplate', { reportType: 'ExportDocument', name: '私人明细属性验收', sourceTemplatePath: packing.templatePath }, {}, ownerSession.accessToken);
  const detailDesign = JSON.parse(detailCopy.contentHtml);
  const detail = detailDesign.layers.flatMap(layer => layer.elements).find(element => element.block?.type === 'DetailTable');
  let releaseCatalog;
  const catalogGate = new Promise(resolve => { releaseCatalog = resolve; });
  const catalogRoute = '**/api/reports/templates?*';
  await page.route(catalogRoute, async route => { await catalogGate; await route.continue(); });
  try {
    await page.goto(`${url}/#/reports/templates?reportType=ExportDocument&userTemplateId=${detailCopy.id}`);
    await page.reload();
    await page.locator(`[data-v3-element-id="${detail.id}"]`).waitFor();
    const catalogResponse = page.waitForResponse(response => response.url().includes('/api/reports/templates?'));
    releaseCatalog(); assert.equal((await catalogResponse).status(),200);
  } finally { releaseCatalog(); await page.unroute(catalogRoute); }
  await page.getByRole('tab', { name: '可视化设计', exact: true }).click();
  await page.locator(`[data-v3-element-id="${detail.id}"]`).click();
  const properties = page.locator('.new-report-detail-properties');
  await properties.getByLabel('标题', { exact: true }).fill('货物说明（验收）');
  await properties.getByLabel('标题', { exact: true }).press('Enter');
  await properties.getByRole('tab', { name: '表格样式', exact: true }).click();
  const styles = properties.locator('[role=tabpanel] > div:not([hidden])');
  await styles.locator('label').filter({ has: page.getByText('设置文字样式', { exact: true }) }).locator('select').selectOption('headerStyle');
  await styles.getByLabel('字号', { exact: true }).fill('12');
  await styles.getByLabel('字号', { exact: true }).press('Tab');
  const detailSaving = page.waitForResponse(response => response.url().includes(`/api/reports/user-templates/${detailCopy.id}`) && response.request().method() === 'PUT');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const detailSaved = await (await detailSaving).json();
  const savedTable = JSON.parse(detailSaved.contentHtml).layers.flatMap(layer => layer.elements).find(element => element.id === detail.id).block;
  assert.equal(savedTable.columns[0].title, '货物说明（验收）');
  assert.equal(savedTable.headerStyle.fontSizePt, 12);
  assert.deepEqual(savedTable.bodyStyle, detail.block.bodyStyle);
  assert.deepEqual(savedTable.summaryRow, detail.block.summaryRow);
  await page.screenshot({ path: path.join(output, 'private-detail-style-saved.png'), fullPage: true });
  await page.getByRole('tab', { name: '预览', exact: true }).click();
  await page.getByRole('button', { name: '样例预览', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('iframe[title="模板预览"]')?.srcdoc.includes('<svg'));
  assert((await page.locator('iframe[title="模板预览"]').getAttribute('srcdoc')).includes('货物说明（验收）'));
  await page.screenshot({ path: path.join(output, 'private-detail-native-preview.png'), fullPage: true });
  for (const [username, expected] of [['private-owner', true], ['private-other', false]]) {
    const session = await invoke('Login', { username, password: 'Private-Test-2026' });
    const catalog = await invoke('ListReportTemplates', undefined, {}, session.accessToken);
    assert.equal(catalog.some(template => template.templatePath === `user-template:${copy.id}`), expected);
  }
  const original = await fetch(`${url}/api/reports/templates/content?reportType=ExportDocument&templatePath=${encodeURIComponent(file.templatePath)}`, { headers: { authorization: `Bearer ${admin}` } }).then(response => response.json());
  assert.equal(original.content, file.content);
  const peer = await openPage('private-other', 'Private-Test-2026');
  await peer.waitForURL('**/#/invoices');
  await peer.goto(`${url}/#/reports/templates/manage`);
  await peer.locator('.template-select-field select').waitFor();
  assert.equal(await peer.locator(`option[value="user-template:${copy.id}"]`).count(), 0);
  await peer.screenshot({ path: path.join(output, 'other-user-private-isolation.png'), fullPage: true });
});
