import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspace = path.join(repoRoot, ".codex-runtime", "invoice-list-model-tests");
const entry = path.join(workspace, "entry.ts");
const bundle = path.join(workspace, "bundle.mjs");
fs.rmSync(workspace, { recursive: true, force: true });
fs.mkdirSync(workspace, { recursive: true });
const modelPath = path.join(repoRoot, "apps", "export-doc-web", "src", "features", "invoices", "invoiceListModels.ts").replaceAll("\\", "/");
const fileNamesPath = path.join(repoRoot, "apps", "export-doc-web", "src", "features", "invoices", "invoiceListFileNames.ts").replaceAll("\\", "/");
fs.writeFileSync(entry, `import * as model from ${JSON.stringify(modelPath)}; import * as fileNames from ${JSON.stringify(fileNamesPath)}; globalThis.__model = model; globalThis.__fileNames = fileNames;`, "utf8");
const esbuild = require(path.join(repoRoot, "apps", "export-doc-web", "node_modules", "esbuild"));
await esbuild.build({ entryPoints: [entry], outfile: bundle, bundle: true, format: "esm", platform: "node", logLevel: "silent" });
await import(pathToFileURL(bundle).href);
const m = globalThis.__model;
const names = globalThis.__fileNames;
const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(m.buildDefaultCopyInvoiceNo(" INV-1 ") === "INV-1副本", "copy number");
assert(m.validateInvoiceCopyDraft({ newInvoiceNo: " " }) === "新发票号不能为空。", "copy validation");
assert(m.normalizeRequiredPackagePath(" a.edpkg ").value === "a.edpkg", "path trim");
assert(m.validateInvoiceTransferImportDraft({ packagePath: "a", previewResponse: null }) === "请先预览单据包。", "preview validation");
assert(m.formatReviewSeverity(2) === "错误" && m.formatReviewSeverityKey(1) === "warning", "severity");
assert(m.formatSingleWindowBusinessType("CustomsCoo") === "COO", "business type");
const previewResponse = { preview: { invoiceExists: true, invoiceMatches: false, invoiceNo: " INV-2 " } };
const transferDraft = m.createInvoiceTransferImportDraft("package.edpkg", previewResponse);
assert(transferDraft.conflictAction === "NewInvoiceNo" && transferDraft.newInvoiceNo === "INV-2_IMPORTED", "transfer conflict draft");
const matchedDraft = m.createInvoiceTransferImportDraft("package.edpkg", { preview: { invoiceExists: true, invoiceMatches: true, invoiceNo: "INV-2" } });
assert(matchedDraft.conflictAction === "Skip", "matching transfer draft");
const excelMessage = m.buildExcelImportRouteSuccessMessage({ success: true, invoice: { invoiceNo: "INV", customerNameEN: "Buyer" }, analysisReport: { analyzerId: "rust-calamine", confidence: 1.5, selectedWorksheetName: "Sheet1" } });
assert(excelMessage.includes("Rust Excel 分析 100%") && excelMessage.includes("发票号、收货人"), "excel success message");
const errorMessage = m.buildExcelImportRouteSuccessMessage({ success: false, errors: ["错误一", "错误二", "错误三"] });
assert(errorMessage.includes("3 个问题") && !errorMessage.includes("错误三"), "excel error summary");
const review = { groups: [{ groupKey: "A", canAutoRepair: false, issues: [{ canAutoRepair: true }] }, { groupKey: " ", canAutoRepair: true, issues: [] }] };
assert(JSON.stringify(m.getAutoRepairGroupKeys(review)) === JSON.stringify(["A"]), "repair group keys");
assert(m.matchesSingleWindowReview(8, "CustomsCoo", 8, "CustomsCoo", { groups: [] }), "review match");
assert(!m.matchesSingleWindowReview(8, "CustomsCoo", 9, "CustomsCoo", { groups: [] }), "review mismatch");
assert(names.sanitizePackageFileName(' INV:01. ') === "INV_01", "file name sanitize");
assert(names.buildSingleWindowPackageDefaultFileName({ id: 1, invoiceNo: "INV/01" }, "AgentConsignment") === "INV_01_ACD.swpkg", "single-window file name");
process.stdout.write("invoice-list-model tests passed\n");
