import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { cargoExampleExecutable } from './lib/cargo-paths.mjs';
import { locateChromeForTesting } from './lib/report-regression-common.mjs';
import { spawnProcessTree, stopProcessTree } from './lib/child-process-tree.mjs';

const repo = path.resolve(import.meta.dirname, '..');
const require = createRequire(path.join(repo, 'apps/export-doc-web/package.json'));
const { chromium } = require('playwright');
const output = path.join(repo, 'artifacts/communication-ui', String(Date.now()));
fs.mkdirSync(output, { recursive: true });
const server = spawnProcessTree(cargoExampleExecutable(repo, 'office_review'), [path.join(output, 'Data')], { cwd: repo, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
let browser, financeBrowser;
const spec = JSON.parse(fs.readFileSync(path.join(repo, 'crates/export-doc-contracts/src/openapi.json'), 'utf8'));
const operations = new Map(Object.entries(spec.paths).flatMap(([route, methods]) => Object.entries(methods).map(([method, op]) => [op.operationId, { route, method }])));
try {
  const url = await new Promise((resolve, reject) => {
    let log = '';
    const timer = setTimeout(() => reject(new Error(`HTTP fixture startup timeout: ${log}`)), 60000);
    const fail = error => { clearTimeout(timer); reject(error); };
    server.once('error', fail); server.once('exit', code => fail(new Error(`HTTP fixture exited ${code}: ${log}`)));
    server.stderr.on('data', chunk => { log += chunk; });
    server.stdout.on('data', chunk => { log += chunk; const match = log.match(/\{"url":"([^"]+)"\}/u); if (match) { clearTimeout(timer); resolve(match[1]); } });
  });
  const invoke = async (id, body, parameters = {}, token = '') => {
    const op = operations.get(id); assert(op, `Unknown operation ${id}`);
    const route = op.route.replace(/\{([^}]+)\}/gu, (_, key) => encodeURIComponent(parameters[key]));
    const response = await fetch(url + route, { method: op.method.toUpperCase(), headers: { ...(token ? { authorization: `Bearer ${token}` } : {}), ...(body ? { 'content-type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    assert.equal(response.status, 200, `${id}: ${await response.clone().text()}`);
    return response.json();
  };
  browser = await chromium.launchPersistentContext(path.join(output, 'Chrome'), { executablePath: locateChromeForTesting(repo), headless: true, viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await browser.newPage();
  page.setDefaultTimeout(30000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.locator('input[autocomplete=username]').fill('oa-review');
  await page.locator('input[autocomplete=current-password]').fill('Review-2026-Test');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('.login-submit-button').waitFor({ state: 'hidden' });
  const navigate = async route => { await page.goto(`${url}/#${route}`); };
  await navigate('/office/announcements');
  await page.getByRole('button', { name: '新建公告', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('公告标题', { exact: true }).fill('国庆安排与制度确认');
  await dialog.getByLabel('公告正文').fill('请各部门核对安排。\n第二行：<script>仅作为文字显示</script>');
  await dialog.getByLabel('可见范围').selectOption('GENERAL');
  await dialog.getByLabel('置顶公告', { exact: true }).check();
  const attachment = path.join(output, 'notice.pdf');
  fs.writeFileSync(attachment, '%PDF-1.7\n1 0 obj<</Type/Catalog>>endobj\n%%EOF\n');
  await dialog.locator('input[type=file]').setInputFiles(attachment);
  await dialog.getByRole('button', { name: '保存草稿', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.locator('.oa-attachments').getByText('notice.pdf', { exact: true }).waitFor();
  const id = new URLSearchParams(page.url().split('?')[1]).get('announcementId'); assert(id);
  await navigate('/office/notifications');
  await page.getByRole('heading', { name: /站内通知/ }).waitFor();
  await navigate('/office/announcements');
  await page.getByRole('button', { name: '继续编辑', exact: true }).click();
  dialog = page.getByRole('dialog');
  assert.equal(await dialog.getByLabel('公告标题', { exact: true }).inputValue(), '国庆安排与制度确认');
  await dialog.getByLabel('公告正文').fill('回访草稿继续编辑。\n<script>仅作为文字显示</script>');
  await dialog.getByRole('button', { name: '保存草稿', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.locator('.communication-body').getByText(/回访草稿继续编辑/u).waitFor();
  await page.locator('.oa-attachments').getByText('notice.pdf', { exact: true }).waitFor();
  const publish = async () => { await page.getByRole('button', { name: '发布公告', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: '发布公告', exact: true }).click(); await page.getByRole('dialog').waitFor({ state: 'hidden' }); };
  await publish();
  await page.getByRole('button', { name: '我已阅读并确认', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '已确认阅读' }).waitFor();
  assert.equal(await page.locator('.communication-body script').count(), 0);
  assert((await page.locator('.communication-body').innerText()).includes('<script>'));
  await page.getByText('阅读回执', { exact: true }).click();
  await page.locator('.oa-history').getByText(/验收管理员/u).waitFor();
  await page.screenshot({ path: path.join(output, 'published-receipt.png'), fullPage: true });
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载', exact: true }).click();
  const download = await downloaded; const downloadedPath = path.join(output, 'download.pdf'); await download.saveAs(downloadedPath);
  assert.deepEqual(fs.readFileSync(downloadedPath), fs.readFileSync(attachment));
  const login = await invoke('Login', { username: 'oa-review', password: 'Review-2026-Test' });
  const token = login.accessToken;
  const draftBody = { requestKey: `delete-ui-${Date.now()}`, title: '待删除草稿', body: '误录公告', audienceDepartment: '', isPinned: false, startsAt: new Date(Date.now() - 3600000).toISOString(), expiresAt: new Date(Date.now() + 86400000).toISOString() };
  const removable = await invoke('CreateAnnouncement', draftBody, {}, token);
  await navigate(`/office/announcements?announcementId=${removable.id}`);
  await page.getByRole('button', { name: '删除草稿', exact: true }).click();
  await page.getByRole('dialog').getByLabel('操作原因').fill('清理误录草稿');
  await page.getByRole('dialog').getByRole('button', { name: '删除草稿', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '新建公告', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '待删除草稿', exact: true }).count(), 0);
  await page.screenshot({ path: path.join(output, 'announcement-management.png'), fullPage: true });
  await navigate(`/office/announcements?announcementId=${id}`);
  await page.getByRole('button', { name: '撤回公告', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '删除草稿', exact: true }).count(), 0);
  const row = await invoke('GetAnnouncement', undefined, { id }, token);
  const downloadRoute = operations.get('DownloadAnnouncementAttachment').route.replace('{id}', id).replace('{attachmentId}', row.attachments[0].id);
  assert.equal((await fetch(url + downloadRoute)).status, 401);
  await page.getByRole('button', { name: '撤回公告', exact: true }).click();
  await page.getByRole('dialog').getByLabel('操作原因').fill('修订安排');
  await page.getByRole('dialog').getByRole('button', { name: '撤回公告', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '编辑草稿', exact: true }).click();
  await page.getByRole('dialog').getByLabel('公告正文').fill('修订内容：各部门重新确认。');
  await page.getByRole('dialog').getByRole('button', { name: '保存草稿', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' }); await publish();
  await page.getByRole('button', { name: '我已阅读并确认', exact: true }).waitFor();
  assert((await page.locator('.oa-detail-summary').innerText()).includes('发布版本 2'));
  const people = await invoke('ListPersonnel', undefined, {}, token);
  const person = people.items[0]; assert(person);
  let request = await invoke('CreateGeneralRequest', { requestKey: `notification-ui-${Date.now()}`, employeeId: person.id, title: '站内通知关联申请', reason: '检验审批结果通知', category: 'IT' }, {}, token);
  for (const op of ['SubmitGeneralRequest', 'ApproveGeneralRequest']) request = await invoke(op, { expectedVersion: request.versionNumber, note: '验收通过' }, { id: request.id }, token);
  await navigate('/office/notifications');
  await page.getByRole('heading', { name: '审批通过 · 站内通知关联申请', exact: true }).waitFor();
  await page.getByRole('button', { name: '标记已读', exact: true }).click();
  await page.getByRole('heading', { name: '站内通知 · 0 条未读', exact: true }).waitFor();
  await page.getByRole('link', { name: '查看关联申请', exact: true }).click();
  await page.locator('.oa-detail').getByRole('heading', { name: '站内通知关联申请', exact: true }).waitFor();
  assert(page.url().includes(`requestId=${request.id}`));
  await navigate('/office/notifications');
  await page.locator('[aria-label="站内通知"] .office-resource-card').waitFor();
  await page.screenshot({ path: path.join(output, 'notification-inbox.png'), fullPage: true });
  for (const route of ['/office/notifications', `/office/announcements?announcementId=${id}`]) {
    await navigate(route); await page.locator('.oa-workspace').waitFor();
    await page.addScriptTag({ path: require.resolve('axe-core/axe.min.js') });
    const violations = await page.evaluate(async () => (await window.axe.run(document.querySelector('.oa-workspace'))).violations.filter(v => ['critical', 'serious'].includes(v.impact)));
    assert.deepEqual(violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })), []);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.communication-body').waitFor();
  await page.screenshot({ path: path.join(output, 'announcement-mobile.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile page must not overflow');
  const financeName = `finance-ui-${Date.now()}`;
  await invoke('createUserAccount', { username: financeName, fullName: '财务接收验收', role: 'Finance', companyScope: 'DEFAULT', departmentId: 'GENERAL', isActive: true, resetPassword: 'Finance-Review-2026' }, {}, token);
  const businessUser = await invoke('getCurrentUser', undefined, {}, token);
  const expenseBody = { requestKey: `expense-ui-${Date.now()}`, employeeId: person.id, title: '已批准报销财务接收', reason: '核对凭证并移交独立财务软件', currency: 'CNY', lines: [{ category: 'Travel', spentOn: businessUser.businessDate, description: '市内交通', amount: '12.35' }] };
  let expense = await invoke('CreateExpenseRequest', expenseBody, {}, token);
  const privateDraft = await invoke('CreateExpenseRequest', { ...expenseBody, requestKey: `private-${Date.now()}`, title: '未批准报销不得向财务公开' }, {}, token);
  const form = new FormData(); form.set('expectedVersion', String(expense.versionNumber)); form.set('file', new Blob([fs.readFileSync(attachment)], { type: 'application/pdf' }), 'expense.pdf');
  const upload = await fetch(url + operations.get('UploadAttachmentToExpenseRequest').route.replace('{id}', expense.id), { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: form });
  assert.equal(upload.status, 200); expense = await upload.json();
  for (const op of ['SubmitExpenseRequest', 'ApproveExpenseRequest']) expense = await invoke(op, { expectedVersion: expense.versionNumber, note: '审批通过' }, { id: expense.id }, token);
  financeBrowser = await chromium.launchPersistentContext(path.join(output, 'FinanceChrome'), { executablePath: locateChromeForTesting(repo), headless: true, viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const financePage = await financeBrowser.newPage(); financePage.setDefaultTimeout(30000);
  await financePage.goto(url);
  await financePage.locator('input[autocomplete=username]').fill(financeName);
  await financePage.locator('input[autocomplete=current-password]').fill('Finance-Review-2026');
  await financePage.getByRole('button', { name: '登录', exact: true }).click();
  await financePage.locator('.login-submit-button').waitFor({ state: 'hidden' });
  await financePage.goto(`${url}/#/office/requests/expense`);
  await financePage.locator('.office-tabs').getByRole('button', { name: '财务接收', exact: true }).waitFor();
  await financePage.getByRole('button', { name: expenseBody.title, exact: true }).waitFor();
  assert.equal(await financePage.getByRole('button', { name: privateDraft.title, exact: true }).count(), 0);
  await financePage.screenshot({ path: path.join(output, 'finance-queue.png'), fullPage: true });
  await financePage.getByRole('button', { name: expenseBody.title, exact: true }).click();
  await financePage.getByRole('heading', { name: '报销凭证', exact: true }).waitFor();
  assert.equal(await financePage.getByRole('button', { name: '编辑草稿', exact: true }).count(), 0);
  assert.equal(await financePage.getByRole('button', { name: '批准', exact: true }).count(), 0);
  const expenseDownload = financePage.waitForEvent('download');
  await financePage.getByRole('button', { name: '下载', exact: true }).click();
  await (await expenseDownload).saveAs(path.join(output, 'finance-receipt.pdf'));
  assert.deepEqual(fs.readFileSync(path.join(output, 'finance-receipt.pdf')), fs.readFileSync(attachment));
  await financePage.getByRole('button', { name: '财务接收', exact: true }).click();
  await financePage.getByRole('dialog').getByLabel('处理说明').fill('凭证已核对，财务接收编号 FIN-UI-001');
  await financePage.getByRole('dialog').getByRole('button', { name: '财务接收', exact: true }).click();
  await financePage.getByRole('dialog').waitFor({ state: 'hidden' });
  await financePage.getByText('财务交接已登记', { exact: true }).waitFor();
  await financePage.getByText('审批与办理记录', { exact: true }).click();
  await financePage.getByText('凭证已核对，财务接收编号 FIN-UI-001', { exact: true }).waitFor();
  await financePage.screenshot({ path: path.join(output, 'finance-received.png'), fullPage: true });
  await financePage.addScriptTag({ path: require.resolve('axe-core/axe.min.js') });
  assert.deepEqual(await financePage.evaluate(async () => (await window.axe.run(document.querySelector('.oa-workspace'))).violations.filter(v => ['critical', 'serious'].includes(v.impact)).map(v => v.id)), []);
  assert.deepEqual(errors, []);
  console.log(`Announcements and notification React/HTTP workflows passed: ${output}`);
} catch (error) {
  const page=browser?.pages().at(-1);
  if (page) { await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{}); fs.writeFileSync(path.join(output,'failure.txt'),await page.locator('body').innerText().catch(()=>'')); }
  throw error;
} finally {
  await financeBrowser?.close();
  await browser?.close();
  await stopProcessTree(server);
}
