import type {
  ReportBorderStyle,
  ReportDesignerReportType,
  ReportDesignerSchema,
  ReportSection,
  ReportTextStyle,
} from "./reportDesignerSchema.ts";
import { createGridBlock } from "./reportDesignerMutations.ts";
import {
  portableReportSansFontFamily,
  portableReportSerifFontFamily,
} from "../../app/typographyPolicy.ts";

const baseTextStyle: ReportTextStyle = {
  fontSizePt: 10,
  align: "Left",
  marginTopMm: 1.5,
  marginBottomMm: 1.5,
};

const noBorder: ReportBorderStyle = {
  color: "#333333",
  widthPx: 0,
  top: false,
  right: false,
  bottom: false,
  left: false,
};

const bottomLine: ReportBorderStyle = {
  color: "#333333",
  widthPx: 1,
  top: false,
  right: false,
  bottom: true,
  left: false,
};

export function createDefaultReportDesignerSchema(reportType: ReportDesignerReportType): ReportDesignerSchema {
  if (reportType === "PaymentVoucher") {
    return createPaymentVoucherSchema();
  }

  return createExportInvoiceSchema();
}

function createExportInvoiceSchema(): ReportDesignerSchema {
  return {
    version: 2,
    reportType: "ExportDocument",
    page: {
      size: "A4",
      orientation: "Portrait",
      marginTopMm: 8,
      marginRightMm: 8,
      marginBottomMm: 8,
      marginLeftMm: 8,
      fontFamily: portableReportSansFontFamily,
      fontSizePt: 9,
    },
    sections: [
      {
        id: "section-header",
        type: "Header",
        print: createSectionPrintSettings("Header"),
        blocks: [
          {
            id: "block-exporter-name",
            type: "Field",
            label: "",
            fieldPath: "Exporter.ExporterNameEN",
            fallbackText: "NINGBO BRIDGE IMP & EXP CO.,LTD",
            style: {
              ...baseTextStyle,
              fontSizePt: 13,
              bold: true,
              align: "Center",
              marginBottomMm: 4,
            },
            border: noBorder,
          },
          {
            id: "block-title",
            type: "Text",
            text: "COMMERCIAL INVOICE",
            style: {
              ...baseTextStyle,
              fontSizePt: 16,
              bold: true,
              align: "Center",
              marginBottomMm: 5,
            },
            border: noBorder,
          },
        ],
      },
      {
        id: "section-body",
        type: "Body",
        print: createSectionPrintSettings("Body"),
        blocks: [
          {
            id: "block-party-and-invoice",
            type: "Row",
            marginTopMm: 1,
            marginBottomMm: 1.5,
            columns: [
              {
                id: "row-col-customer",
                contentKind: "Field",
                text: "",
                label: "TO:M/S",
                fieldPath: "Customer.CustomerNameEN",
                fallbackText: "Customer name",
                widthPercent: 58,
                style: {
                  ...baseTextStyle,
                  bold: true,
                  align: "Left",
                },
                border: noBorder,
              },
              {
                id: "row-col-invoice-no",
                contentKind: "Field",
                text: "",
                label: "Invoice No.",
                fieldPath: "Invoice.InvoiceNo",
                fallbackText: "INV-0001",
                widthPercent: 42,
                style: {
                  ...baseTextStyle,
                  bold: true,
                  align: "Right",
                },
                border: bottomLine,
              },
            ],
          },
          {
            id: "block-contract-and-date",
            type: "Row",
            marginTopMm: 1,
            marginBottomMm: 1.5,
            columns: [
              {
                id: "row-col-ports",
                contentKind: "Text",
                text: "From: NINGBO CHINA",
                label: "",
                fieldPath: "",
                fallbackText: "",
                widthPercent: 58,
                style: baseTextStyle,
                border: bottomLine,
              },
              {
                id: "row-col-date",
                contentKind: "Field",
                text: "",
                label: "Date",
                fieldPath: "Invoice.InvoiceDate",
                fallbackText: "",
                widthPercent: 42,
                style: {
                  ...baseTextStyle,
                  align: "Right",
                },
                border: bottomLine,
              },
            ],
          },
        ],
      },
      {
        id: "section-footer",
        type: "Footer",
        print: createSectionPrintSettings("Footer"),
        blocks: [
          {
            id: "block-footer-note",
            type: "Text",
            text: "Generated by ExportDocManager structured report designer.",
            style: {
              ...baseTextStyle,
              fontSizePt: 8,
              align: "Center",
            },
            border: noBorder,
          },
        ],
      },
    ],
  };
}

function createPaymentVoucherSchema(): ReportDesignerSchema {
  return {
    version: 2,
    reportType: "PaymentVoucher",
    page: {
      size: "A4",
      orientation: "Portrait",
      marginTopMm: 16,
      marginRightMm: 14,
      marginBottomMm: 16,
      marginLeftMm: 14,
      fontFamily: portableReportSerifFontFamily,
      fontSizePt: 10,
    },
    sections: [
      {
        id: "section-header",
        type: "Header",
        print: createSectionPrintSettings("Header"),
        blocks: [
          {
            id: "block-title",
            type: "Text",
            text: "宁波布利杰进出口有限公司付款单（出口贸易专用）",
            style: {
              ...baseTextStyle,
              fontSizePt: 15,
              bold: true,
              align: "Center",
              marginBottomMm: 2,
            },
            border: noBorder,
          },
          {
            id: "block-payment-id-row",
            type: "Row",
            marginTopMm: 1,
            marginBottomMm: 2,
            columns: [
              {
                id: "payment-row-department",
                contentKind: "Field",
                text: "",
                label: "部门",
                fieldPath: "Payment.Department",
                fallbackText: "",
                widthPercent: 33.3,
                style: baseTextStyle,
                border: bottomLine,
              },
              {
                id: "payment-row-project",
                contentKind: "Field",
                text: "",
                label: "业务/项目",
                fieldPath: "Payment.InvoiceNo",
                fallbackText: "",
                widthPercent: 33.3,
                style: baseTextStyle,
                border: bottomLine,
              },
              {
                id: "payment-row-date",
                contentKind: "Field",
                text: "",
                label: "日期",
                fieldPath: "Payment.PaymentDate",
                fallbackText: "",
                widthPercent: 33.4,
                style: {
                  ...baseTextStyle,
                  align: "Right",
                },
                border: bottomLine,
              },
            ],
          },
        ],
      },
      {
        id: "section-body",
        type: "Body",
        print: createSectionPrintSettings("Body"),
        blocks: [createGridBlock("PaymentVoucher")],
      },
      {
        id: "section-footer",
        type: "Footer",
        print: createSectionPrintSettings("Footer"),
        blocks: [],
      },
    ],
  };
}

function createSectionPrintSettings(sectionType: ReportSection["type"]) {
  if (sectionType === "Body") {
    return {
      repeatOnEveryPage: false,
      keepTogether: false,
      pinToPageBottom: false,
      minHeightMm: 0,
    };
  }

  return {
    repeatOnEveryPage: true,
    keepTogether: true,
    pinToPageBottom: sectionType === "Footer",
    minHeightMm: sectionType === "Header" ? 22 : 14,
  };
}

function createPaymentTextColumn(id: string, text: string, widthPercent: number) {
  return {
    id,
    contentKind: "Text" as const,
    text,
    label: "",
    fieldPath: "",
    fallbackText: "",
    widthPercent,
    style: {
      ...baseTextStyle,
      align: "Center" as const,
    },
    border: {
      color: "#333333",
      widthPx: 1,
      top: true,
      right: true,
      bottom: true,
      left: true,
    },
  };
}

function createPaymentFieldColumn(id: string, fieldPath: string, widthPercent: number) {
  return {
    id,
    contentKind: "Field" as const,
    text: "",
    label: "",
    fieldPath,
    fallbackText: "",
    widthPercent,
    style: {
      ...baseTextStyle,
      align: "Right" as const,
    },
    border: {
      color: "#333333",
      widthPx: 1,
      top: true,
      right: true,
      bottom: true,
      left: true,
    },
  };
}
