<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ExportDocManager.Infrastructure.Excel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="ExcelDataReader" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExportDocManager.Application\ExportDocManager.Application.csproj" />
    <ProjectReference Include="..\ExportDocManager.Domain\ExportDocManager.Domain.csproj" />
    <ProjectReference Include="..\ExportDocManager.Infrastructure\ExportDocManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
