use super::{Operation, Result, array, quoted, required, text};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::{collections::BTreeSet, fmt::Write};

fn snake(value: &str) -> String {
    let chars: Vec<_> = value.chars().collect();
    let mut result = String::new();
    for (index, c) in chars.iter().enumerate() {
        if c.is_uppercase()
            && index > 0
            && (chars[index - 1].is_lowercase()
                || chars[index - 1].is_numeric()
                || chars.get(index + 1).is_some_and(|next| next.is_lowercase()))
        {
            result.push('_');
        }
        result.extend(c.to_lowercase());
    }
    result
}
fn field_name(value: &str) -> String {
    let name = snake(value);
    if [
        "type", "ref", "self", "match", "loop", "move", "default", "use", "in",
    ]
    .contains(&name.as_str())
    {
        format!("r#{name}")
    } else {
        name
    }
}
fn nullable(schema: &Value) -> bool {
    array(&schema["type"]).iter().any(|t| t == "null")
        || schema["nullable"] == true
        || array(&schema["anyOf"]).iter().any(|t| t["type"] == "null")
}
pub fn rust_type(schema: &Value, optional: bool) -> String {
    let alternatives: Vec<_> = array(
        schema
            .get("anyOf")
            .or_else(|| schema.get("oneOf"))
            .unwrap_or(&Value::Null),
    )
    .iter()
    .filter(|s| s["type"] != "null")
    .collect();
    let has_type =
        |kind: &str| schema["type"] == kind || array(&schema["type"]).iter().any(|t| t == kind);
    let result = if let Some(reference) = schema["$ref"].as_str() {
        reference.rsplit('/').next().unwrap().into()
    } else if schema["enum"]
        .as_array()
        .is_some_and(|a| a.iter().all(Value::is_string))
    {
        "String".into()
    } else if alternatives.len() == 1 {
        rust_type(alternatives[0], false)
    } else if has_type("integer") {
        "i64".into()
    } else if has_type("number") {
        "rust_decimal::Decimal".into()
    } else if has_type("string") {
        "String".into()
    } else if has_type("boolean") {
        "bool".into()
    } else if schema["type"] == "array" {
        format!("Vec<{}>", rust_type(&schema["items"], false))
    } else if schema["type"] == "object" && schema["additionalProperties"].is_object() {
        format!(
            "std::collections::BTreeMap<String, {}>",
            rust_type(&schema["additionalProperties"], false)
        )
    } else {
        "serde_json::Value".into()
    };
    if optional || nullable(schema) {
        format!("Option<{result}>")
    } else {
        result
    }
}
fn collect(value: &Value, schemas: &Value, names: &mut BTreeSet<String>) {
    if let Some(reference) = value["$ref"].as_str() {
        let name = reference.rsplit('/').next().unwrap();
        if names.insert(name.into()) {
            collect(&schemas[name], schemas, names);
        }
    }
    match value {
        Value::Object(o) => {
            for v in o.values() {
                collect(v, schemas, names);
            }
        }
        Value::Array(a) => {
            for v in a {
                collect(v, schemas, names);
            }
        }
        _ => {}
    }
}
fn response(operation: &Value) -> Value {
    operation["responses"]
        .as_object()
        .and_then(|r| {
            r.iter()
                .filter(|(code, _)| code.len() == 3 && code.starts_with('2'))
                .min_by_key(|(code, _)| *code)
        })
        .map(|(_, v)| v["content"]["application/json"]["schema"].clone())
        .unwrap_or(Value::Null)
}
pub fn generate(document: &Value, operations: &[Operation<'_>]) -> Result<(String, String, usize)> {
    if array(&document["x-exportdoc-permissions"]["resources"]).is_empty() {
        return Err("Missing permission catalog".into());
    }
    if text(&document["x-exportdoc-configuration"]["defaults"]["system"]["appName"]).is_empty() {
        return Err("Missing configuration defaults".into());
    }
    let mut sorted: Vec<_> = operations.iter().collect();
    sorted.sort_by_key(|op| op.id.to_lowercase());
    let mut names = BTreeSet::new();
    for op in &sorted {
        collect(op.value, &document["components"]["schemas"], &mut names);
    }
    let schemas: serde_json::Map<_, _> = names
        .iter()
        .map(|name| {
            (
                name.clone(),
                document["components"]["schemas"][name].clone(),
            )
        })
        .collect();
    let digest = Sha256::digest(serde_json::to_vec(document)?)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    let mut output = format!(
        "// @generated by export-doc-contracts Rust generate_clients from official /openapi/v1.json\n// Do not edit. OpenAPI SHA-256: {digest}\n#![allow(dead_code)]\nuse serde::{{Deserialize, Serialize}};\n\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct Operation {{ pub id: &'static str, pub method: &'static str, pub path: &'static str, pub requires_authentication: bool }}\n\n"
    );
    let mut contracts = serde_json::Map::new();
    let mut constants = Vec::new();
    for op in sorted {
        let constant = snake(op.id).to_uppercase();
        if constants.contains(&constant) {
            return Err(format!("Duplicate Rust operation: {}", op.id).into());
        }
        let auth = op.value["x-exportdoc-policy"]["requiresAuthentication"]
            .as_bool()
            .ok_or("Missing authentication policy")?;
        writeln!(output, "pub const {constant}: Operation = Operation {{ id: {}, method: {}, path: {}, requires_authentication: {auth} }};", quoted(op.id), quoted(&op.method.to_uppercase()), quoted(op.path)).unwrap();
        constants.push(constant);
        let mut chars = op.id.chars();
        let name = chars.next().unwrap().to_uppercase().to_string() + chars.as_str();
        let request = &op.value["requestBody"]["content"]["application/json"]["schema"];
        let response = response(op.value);
        if !request.is_null() {
            writeln!(
                output,
                "pub type {name}Body = {};",
                rust_type(request, false)
            )
            .unwrap();
        }
        if !response.is_null() {
            writeln!(
                output,
                "pub type {name}Response = {};",
                rust_type(&response, false)
            )
            .unwrap();
        }
        contracts.insert(op.id.into(), json!({"policy":op.value["x-exportdoc-policy"], "office":op.value["x-exportdoc-office"], "parameters":op.value.get("parameters").cloned().unwrap_or(json!([])), "requestBody":op.value["requestBody"], "responses":op.value["responses"], "request":request, "response":response}));
    }
    writeln!(
        output,
        "\npub const ALL_OPERATIONS: &[Operation] = &[{}];\n",
        constants.join(",")
    )
    .unwrap();
    for (name, schema) in &schemas {
        let Some(properties) = schema["properties"].as_object() else {
            writeln!(output, "pub type {name} = {};\n", rust_type(schema, false)).unwrap();
            continue;
        };
        writeln!(output, "#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]\npub struct {name} {{").unwrap();
        for (key, value) in properties {
            let optional = !required(schema, key);
            writeln!(
                output,
                "    #[serde(rename = {}{})]\n    pub {}: {},",
                quoted(key),
                if optional || nullable(value) {
                    ", default, skip_serializing_if = \"Option::is_none\""
                } else {
                    ""
                },
                field_name(key),
                rust_type(value, optional)
            )
            .unwrap();
        }
        output.push_str("    #[serde(flatten)]\n    pub extra: std::collections::BTreeMap<String, serde_json::Value>,\n}\n\n");
    }
    let contract = json!({"source":"official /openapi/v1.json", "digest":digest, "configuration":document["x-exportdoc-configuration"], "permissions":document["x-exportdoc-permissions"], "operations":contracts, "schemas":schemas});
    Ok((
        output,
        serde_json::to_string_pretty(&contract)? + "\n",
        names.len(),
    ))
}
