use super::*;
use serde_json::json;

#[test]
fn complete_contract_preserves_types_requests_runtime_and_endpoint_metadata() {
    let document = export_doc_contracts::openapi::document();
    let generated = generate(&document).unwrap();
    let web =
        include_str!("../../../../apps/export-doc-web/src/api/generated/exportDocManagerApi.ts");
    // Only the producer comment changes when migrating from the previous generator.
    let without_producer = |value: &str| {
        value
            .lines()
            .filter(|line| !line.starts_with("// Generated by "))
            .collect::<Vec<_>>()
            .join("\n")
    };
    assert_eq!(without_producer(&generated.web), without_producer(web));
    let contract: Value = serde_json::from_str(&generated.contract).unwrap();
    let previous: Value =
        serde_json::from_str(include_str!("../../src/generated_contract.json")).unwrap();
    for key in ["configuration", "permissions", "operations", "schemas"] {
        assert_eq!(contract[key], previous[key], "contract projection: {key}");
    }
    let operations = contract["operations"].as_object().unwrap();
    assert_eq!(operations.len(), generated.operation_count);
    for item in document["paths"].as_object().unwrap().values() {
        for method in ["get", "post", "put", "delete", "patch"] {
            if let Some(op) = item.get(method) {
                let projected = &operations[text(&op["operationId"])];
                for (source, target) in [
                    ("x-exportdoc-policy", "policy"),
                    ("responses", "responses"),
                    ("requestBody", "requestBody"),
                ] {
                    assert_eq!(op[source], projected[target]);
                }
            }
        }
    }
}

#[test]
fn multipart_binary_headers_defaults_and_nullable_items_are_preserved() {
    let mut doc = export_doc_contracts::openapi::document();
    doc["paths"] = json!({"/files/{id}": {"post": {
        "operationId":"uploadFile", "x-exportdoc-policy":{"requiresAuthentication":true},
        "parameters":[{"name":"id","in":"path","schema":{"type":"string"}},{"name":"X-Revision","in":"header","required":true,"schema":{"type":"integer"}}],
        "requestBody":{"required":true,"content":{"multipart/form-data":{}}},
        "responses":{"200":{"content":{"application/pdf":{"schema":{"type":"string","format":"binary"}}}}}
    }}});
    doc["components"]["schemas"] = json!({"Example":{"type":"object","required":["name"],"properties":{"name":{"type":"string","default":"中文"},"enabled":{"type":"boolean"}}}});
    let generated = generate(&doc).unwrap();
    for expected in [
        "body: FormData;",
        "Promise<Blob>",
        "encodePath(request.id)",
        "mergeHeaders",
        "\"X-Revision\": number;",
        "name: string;",
        "enabled?: boolean;",
        "name: \"中文\"",
    ] {
        assert!(generated.web.contains(expected), "missing {expected}");
    }
    assert_eq!(
        typescript::schema_type(
            &json!({"type":"array","items":{"anyOf":[{"type":"string"},{"type":"null"}]}})
        ),
        "(string | null)[]"
    );
    assert_eq!(
        native::rust_type(&json!({"type":["number","null"]}), false),
        "Option<rust_decimal::Decimal>"
    );
}

#[test]
fn invalid_references_duplicate_names_and_missing_security_fail_closed() {
    let original = export_doc_contracts::openapi::document();
    let mut doc = original.clone();
    doc["components"]["schemas"]["Bad"] = json!({"$ref":"#/components/schemas/Missing"});
    assert!(generate(&doc).is_err());
    let mut doc = original.clone();
    let operation =
        json!({"operationId":"same", "x-exportdoc-policy":{"requiresAuthentication":true}});
    doc["paths"] = json!({"/a":{"get":operation},"/b":{"post":operation}});
    assert!(generate(&doc).is_err());
    let mut doc = original.clone();
    doc["paths"] = json!({"/a":{"get":{"operationId":"test"}}});
    assert!(generate(&doc).is_err());
    let mut doc = original;
    doc["x-exportdoc-permissions"] = Value::Null;
    assert!(generate(&doc).is_err());
}
